using System.Diagnostics;
using System.Net;
using System.Net.Sockets;
using System.Security.Principal;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;
using System.Collections.Concurrent;
namespace MelavoClient;
sealed partial class Client:Form {
 readonly ModernInput url=new(){Dock=DockStyle.Fill,UseSystemPasswordChar=true,PlaceholderText="لینک سابسکریپشن HTTPS"};
 readonly ModernInput name=new(){Width=170,PlaceholderText="نام گروه"};
 readonly ModernSelect groups=new(){Width=220,DropDownStyle=ComboBoxStyle.DropDownList};
 readonly ServerList servers=new(){Dock=DockStyle.Fill,RightToLeft=RightToLeft.No};
 readonly ModernButton add=new(){Text="افزودن ساب",AutoSize=true},refresh=new(){Text="آپدیت گروه",AutoSize=true},start=new(){Text="اتصال",AutoSize=true},stop=new(){Text="قطع اتصال",AutoSize=true,Enabled=false};
 readonly ModernToggle tun=new(){Text="حالت TUN",Checked=true};
 readonly Label status=new(){Text="قطع است",Dock=DockStyle.Fill,AutoEllipsis=true};
 readonly ModernInput details=new(){Dock=DockStyle.Fill,Multiline=true,ReadOnly=true,ScrollBars=ScrollBars.Vertical,RightToLeft=RightToLeft.No};
 List<SubscriptionGroup> subscriptions=new();Process? xray,box;string? session;bool busy,updating;readonly CoreJob job=new();
 readonly ConcurrentDictionary<int,ConcurrentQueue<string>> logs=new();
 List<JsonObject> Profiles=>groups.SelectedItem is SubscriptionGroup g?g.Profiles:new();
 bool singleConfigScope;string? selectedSubscriptionId,selectedSingleGroupId;
 readonly ModernButton subscriptionsTab=new(){Text="ساب‌ها",Selected=true},singleConfigsTab=new(){Text="کانفیگ‌های تکی"},shareConfig=new(){Text="اشتراک‌گذاری"};
 static string Core(string name)=>Path.Combine(AppContext.BaseDirectory,"core",name);
 readonly bool preview;
 public Client(bool previewMode=false){
  preview=previewMode;AutoScaleDimensions=new SizeF(96,96);AutoScaleMode=AutoScaleMode.Dpi;
  BuildShell();InitializeConfigMenu();InitializeAutoUpdate();InitializeAppUpdates();
  add.Click+=(_,_)=>ShowSubscriptionDialog();refresh.Click+=async(_,_)=>{if(groups.SelectedItem is SubscriptionGroup g&&IsSubscription(g))await UpdateGroups(new[]{g});};start.Click+=async(_,_)=>await Connect();stop.Click+=(_,_)=>Disconnect();groups.SelectedIndexChanged+=(_,_)=>{if(groups.SelectedItem is SubscriptionGroup g){if(singleConfigScope)selectedSingleGroupId=g.Id;else selectedSubscriptionId=g.Id;}ShowGroup();};servers.SelectedIndexChanged+=(_,_)=>shareConfig.Enabled=servers.SelectedItems.Count>0&&groups.SelectedItem is SubscriptionGroup;subscriptionsTab.Click+=(_,_)=>SetConfigScope(false);singleConfigsTab.Click+=(_,_)=>SetConfigScope(true);shareConfig.Click+=(_,_)=>ShowConfigShare();
  FormClosing+=async(_,e)=>{if(busy||updating){e.Cancel=true;status.Text=L("An operation is running. Please wait.","عملیات در حال اجراست؛ چند لحظه صبر کنید.");return;}if(pingTesting){e.Cancel=true;pingCancellation.Cancel();while(pingTesting)await Task.Delay(50);Close();return;}Disconnect();job.Dispose();};
  Shown+=async(_,_)=>{NormalizeTypography();var workArea=Screen.FromControl(this).WorkingArea;if(Height>workArea.Height-30)Height=workArea.Height-30;if(Width>workArea.Width-30)Width=workArea.Width-30;MinimumSize=new Size(Math.Min(1240,workArea.Width-30),Math.Min(780,workArea.Height-30));MaximumSize=Size.Empty;MaximizedBounds=workArea;CenterToScreen();if(preview){LoadPreview();return;}try{subscriptions=SubscriptionStore.Read();PopulateGroups(null);}catch{details.Text=L("Could not read saved groups. The original file was preserved.","خواندن گروه‌های ذخیره‌شده ناموفق بود. فایل اصلی حفظ شده است.");}if(subscriptions.Any(g=>IsSubscription(g)&&g.AutoUpdate))await UpdateGroups(subscriptions.Where(g=>IsSubscription(g)&&g.AutoUpdate).ToArray());};
  var timer=new System.Windows.Forms.Timer{Interval=1000};timer.Tick+=(_,_)=>{if(!busy&&xray!=null&&(xray.HasExited||(box?.HasExited??false))){var error=CoreError(box?.HasExited==true?box:xray);Disconnect();status.Text=L("Engine stopped; connection closed.","هسته متوقف شد؛ اتصال قطع شد.");details.Text=error;}};timer.Start();FormClosed+=(_,_)=>timer.Dispose();
 }
 void ShowGroup(){if(!fillingServers)FillServers();}
 void SetControls(){bool idle=!busy&&!updating&&!pingTesting&&xray==null;add.Enabled=idle;refresh.Enabled=idle&&!singleConfigScope;manageSubscription.Enabled=idle;subscriptionsTab.Enabled=singleConfigsTab.Enabled=idle;editSubscription.Enabled=idle&&!singleConfigScope&&groups.SelectedItem is SubscriptionGroup;start.Enabled=idle;groups.Enabled=idle;servers.Enabled=!updating;tun.Enabled=idle;deleteSubscription.Enabled=editConfig.Enabled=idle;shareConfig.Enabled=idle&&servers.SelectedItems.Count>0;name.Enabled=idle;url.Enabled=idle;stop.Enabled=!busy&&xray!=null;SyncUi();}
 static List<JsonObject> Parse(string raw){
  raw=raw.Trim().TrimStart('\uFEFF');if(raw.Length==0)throw new Exception("Subscription content is empty.");
  if(raw.StartsWith("{")||raw.StartsWith("[")){
   var node=JsonNode.Parse(raw)!;var profiles=node is JsonArray array?array.Select(x=>x?.AsObject()??throw new Exception("Invalid JSON configuration.")).ToList():new(){node.AsObject()};
   if(profiles.Count==0||profiles.Any(x=>x["outbounds"] is not JsonArray))throw new Exception("Subscription does not contain Xray configurations.");return profiles;
  }
  var lines=raw.Split(new[]{'\r','\n'},StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries).Where(x=>!x.StartsWith('#')&&!x.StartsWith(';')).ToArray();
  var links=new List<string>();foreach(var line in lines){if(line.StartsWith("vless://",StringComparison.OrdinalIgnoreCase)||line.StartsWith("vmess://",StringComparison.OrdinalIgnoreCase)||line.StartsWith("trojan://",StringComparison.OrdinalIgnoreCase))links.Add(line);}
  if(links.Count>0)return links.Select(ParseProxyLink).ToList();
  try{return Parse(System.Text.Encoding.UTF8.GetString(Convert.FromBase64String(raw.Replace('-','+').Replace('_','/').PadRight((raw.Length+3)/4*4,'='))));}catch(Exception e) when(e is FormatException or System.Text.Json.JsonException or InvalidOperationException){throw new Exception("Unsupported format; enter Xray JSON or VLESS, VMess or Trojan links.");}
 }
 static Dictionary<string,string> LinkQuery(Uri uri){var result=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);foreach(var pair in uri.Query.TrimStart('?').Split('&',StringSplitOptions.RemoveEmptyEntries)){var parts=pair.Split('=',2);result[Uri.UnescapeDataString(parts[0].Replace('+',' '))]=parts.Length>1?Uri.UnescapeDataString(parts[1].Replace('+',' ')):"";}return result;}
 static JsonObject ParseProxyLink(string text){
  if(text.StartsWith("vmess://",StringComparison.OrdinalIgnoreCase))return ParseVmessLink(text);
  if(!Uri.TryCreate(text,UriKind.Absolute,out var uri)||uri.Port is <1 or >65535)throw new Exception("Invalid proxy link.");var query=LinkQuery(uri);var name=Uri.UnescapeDataString(uri.Fragment.TrimStart('#'));if(string.IsNullOrWhiteSpace(name))name=$"{uri.Host}:{uri.Port}";
  JsonObject outbound;
  if(uri.Scheme.Equals("vless",StringComparison.OrdinalIgnoreCase)){
   var id=Uri.UnescapeDataString(uri.UserInfo);if(!Guid.TryParse(id,out _))throw new Exception("Invalid VLESS identifier.");var user=new JsonObject{["id"]=id,["encryption"]=query.GetValueOrDefault("encryption","none")};if(query.TryGetValue("flow",out var flow)&&flow.Length>0)user["flow"]=flow;
   outbound=new JsonObject{["protocol"]="vless",["settings"]=new JsonObject{["vnext"]=new JsonArray(new JsonObject{["address"]=uri.Host,["port"]=uri.Port,["users"]=new JsonArray(user)})}};
  }else if(uri.Scheme.Equals("trojan",StringComparison.OrdinalIgnoreCase)){
   var password=Uri.UnescapeDataString(uri.UserInfo);if(password.Length==0)throw new Exception("Trojan password is empty.");outbound=new JsonObject{["protocol"]="trojan",["settings"]=new JsonObject{["servers"]=new JsonArray(new JsonObject{["address"]=uri.Host,["port"]=uri.Port,["password"]=password})}};
  }else throw new Exception("Unsupported proxy link scheme.");
  var network=query.GetValueOrDefault("type",query.GetValueOrDefault("network","tcp")).ToLowerInvariant();var security=query.GetValueOrDefault("security","none").ToLowerInvariant();var stream=new JsonObject{["network"]=network,["security"]=security};
  if(network=="ws"){var ws=new JsonObject{["path"]=query.GetValueOrDefault("path","")};var host=query.GetValueOrDefault("host","");if(host.Length>0)ws["headers"]=new JsonObject{["Host"]=host};stream["wsSettings"]=ws;}
  else if(network=="grpc"){stream["grpcSettings"]=new JsonObject{["serviceName"]=query.GetValueOrDefault("serviceName",query.GetValueOrDefault("path","")),["authority"]=query.GetValueOrDefault("authority","")};}
  else if(network=="httpupgrade"){stream["httpupgradeSettings"]=new JsonObject{["path"]=query.GetValueOrDefault("path",""),["host"]=query.GetValueOrDefault("host","")};}
  else if(network=="tcp"&&query.TryGetValue("headerType",out var header)&&header!="none")stream["tcpSettings"]=new JsonObject{["header"] = new JsonObject{["type"]=header}};
  var serverName=query.GetValueOrDefault("sni",query.GetValueOrDefault("serverName",query.GetValueOrDefault("host",uri.Host)));
  if(security=="tls"){var tls=new JsonObject{["serverName"]=serverName};if(query.TryGetValue("allowInsecure",out var insecure))tls["allowInsecure"]=insecure is "1" or "true";if(query.TryGetValue("fp",out var fingerprint))tls["fingerprint"]=fingerprint;if(query.TryGetValue("alpn",out var alpn))tls["alpn"]=new JsonArray(alpn.Split(',').Select(x=>(JsonNode?)JsonValue.Create(x)).ToArray());stream["tlsSettings"]=tls;}
  else if(security=="reality")stream["realitySettings"]=new JsonObject{["serverName"]=serverName,["publicKey"]=query.GetValueOrDefault("pbk",""),["shortId"]=query.GetValueOrDefault("sid",""),["spiderX"]=query.GetValueOrDefault("spx",""),["fingerprint"]=query.GetValueOrDefault("fp","chrome")};
  outbound["streamSettings"]=stream;var profile=new JsonObject{["remarks"]=name,["outbounds"]=new JsonArray(outbound)};RememberShareLink(profile,text);return profile;
 }
 static JsonObject ParseVmessLink(string text){var encoded=text["vmess://".Length..].Trim();var data=JsonNode.Parse(System.Text.Encoding.UTF8.GetString(Convert.FromBase64String(encoded.Replace('-','+').Replace('_','/').PadRight((encoded.Length+3)/4*4,'='))))!.AsObject();var host=data["add"]?.ToString()??throw new Exception("VMess address is missing.");if(!int.TryParse(data["port"]?.ToString(),out var port)||port is <1 or >65535)throw new Exception("Invalid VMess port.");var id=data["id"]?.ToString()??throw new Exception("VMess identifier is missing.");if(!Guid.TryParse(id,out _))throw new Exception("Invalid VMess identifier.");var user=new JsonObject{["id"]=id,["alterId"]=int.TryParse(data["aid"]?.ToString(),out var aid)?aid:0,["security"]=data["scy"]?.ToString()??"auto"};var outbound=new JsonObject{["protocol"]="vmess",["settings"]=new JsonObject{["vnext"]=new JsonArray(new JsonObject{["address"]=host,["port"]=port,["users"]=new JsonArray(user)})}};var query=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase){{"type",data["net"]?.ToString()??"tcp"},{"security",data["tls"]?.ToString() is "tls" or "reality"?data["tls"]!.ToString():"none"},{"host",data["host"]?.ToString()??""},{"path",data["path"]?.ToString()??""},{"sni",data["sni"]?.ToString()??""},{"fp",data["fp"]?.ToString()??""}};var synthetic=new UriBuilder("vless",host,port){Query=string.Join("&",query.Select(x=>$"{Uri.EscapeDataString(x.Key)}={Uri.EscapeDataString(x.Value)}")),Fragment=data["ps"]?.ToString()??"VMess"}.Uri;var parsed=ParseProxyLink($"vless://{Uri.EscapeDataString(id)}@{synthetic.Host}:{synthetic.Port}{synthetic.Query}#{synthetic.Fragment}");parsed["outbounds"]![0]!["protocol"]="vmess";parsed["outbounds"]![0]!["settings"]!["vnext"]![0]!["users"]![0]!["alterId"]=int.TryParse(data["aid"]?.ToString(),out aid)?aid:0;parsed["outbounds"]![0]!["settings"]!["vnext"]![0]!["users"]![0]!["security"]=data["scy"]?.ToString()??"auto";RememberShareLink(parsed,text);return parsed;
 }
 static async Task<List<JsonObject>> Fetch(string address){if(!Uri.TryCreate(address,UriKind.Absolute,out var u)||u.Scheme!="https")throw new Exception("Enter an HTTPS URL.");using var timeout=new CancellationTokenSource(TimeSpan.FromSeconds(30));using var http=new HttpClient(new HttpClientHandler{UseProxy=false}){Timeout=TimeSpan.FromSeconds(30)};http.DefaultRequestHeaders.UserAgent.ParseAdd("v2rayN/7.0");using var r=await http.GetAsync(u,HttpCompletionOption.ResponseHeadersRead,timeout.Token);r.EnsureSuccessStatusCode();using var input=await r.Content.ReadAsStreamAsync(timeout.Token);using var output=new MemoryStream();var buf=new byte[8192];int n;while((n=await input.ReadAsync(buf,timeout.Token))>0){if(output.Length+n>5000000)throw new Exception("Subscription exceeds the size limit.");output.Write(buf,0,n);}return ReadAccountHeader(r,Parse(System.Text.Encoding.UTF8.GetString(output.ToArray())));}
 async Task UpdateGroups(SubscriptionGroup[] targets){if(busy||updating||xray!=null)return;updating=true;SetControls();int ok=0;var failures=new List<string>();var candidate=subscriptions.Select(CloneGroup).ToList();try{foreach(var original in targets){var g=CloneGroup(candidate.First(x=>x.Id==original.Id));status.Text=L($"Updating {g.Name}…",$"آپدیت {g.Name}…");try{var p=await Fetch(g.Url);g.SourceProfiles=p.Select(x=>(JsonObject)x.DeepClone()).ToList();g.Profiles=p;g.Updated=DateTime.UtcNow;ApplyAccount(g);ApplyOverrides(g);candidate[candidate.FindIndex(x=>x.Id==g.Id)]=g;ok++;}catch(Exception e){failures.Add(g.Name+": "+SafeError(e.Message));}}try{CommitGroups(candidate,(groups.SelectedItem as SubscriptionGroup)?.Id);}catch(Exception e){ok=0;failures.Add(L("Save: ","ذخیره: ")+SafeError(e.Message));}ShowGroup();status.Text=L($"{ok} subscriptions updated"+(failures.Count>0?" · Previous data kept for failed updates":""),$"{ok} گروه آپدیت شد"+(failures.Count>0?"؛ نسخهٔ قبلی گروه‌های ناموفق حفظ شد":""));details.Text=string.Join(Environment.NewLine,failures);}finally{updating=false;SetControls();}}
 static JsonObject XConfig(JsonObject original,int port){var c=(JsonObject)original.DeepClone();c.Remove("_shareLink");c.Remove("_shareSnapshot");if(c["streamSettings"] is JsonObject legacy){if(Outbound(c) is JsonObject output&&output["streamSettings"]==null)output["streamSettings"]=legacy.DeepClone();c.Remove("streamSettings");}var tag=c["inbounds"]?.AsArray().FirstOrDefault(x=>x?["protocol"]?.ToString()=="socks")?["tag"]?.ToString()??"socks";c["inbounds"]=new JsonArray(new JsonObject{["tag"]=tag,["listen"]="127.0.0.1",["port"]=port,["protocol"]="socks",["settings"]=new JsonObject{["auth"]="noauth",["udp"]=true}});c["log"]=JsonNode.Parse("{\"loglevel\":\"warning\"}");return c;}
 static async Task<(JsonObject Config,string[] Exclusions)> Prepare(JsonObject original,int port){
  var config=XConfig(original,port);var exclusions=new HashSet<string>();
  using var timeout=new CancellationTokenSource(TimeSpan.FromSeconds(15));
  async Task<string> Resolve(string host){if(IPAddress.TryParse(host,out var literal)){exclusions.Add(literal+(literal.AddressFamily==AddressFamily.InterNetwork?"/32":"/128"));return literal.ToString();}var addresses=await Dns.GetHostAddressesAsync(host,timeout.Token);var address=addresses.FirstOrDefault(x=>x.AddressFamily==AddressFamily.InterNetwork)??addresses.FirstOrDefault()??throw new Exception("Could not resolve the server address.");exclusions.Add(address+(address.AddressFamily==AddressFamily.InterNetwork?"/32":"/128"));return address.ToString();}
  foreach(var item in config["outbounds"]!.AsArray()){
   if(item is not JsonObject outbound||outbound["settings"] is not JsonObject settings)continue;
   foreach(var key in new[]{"vnext","servers"})if(settings[key] is JsonArray endpoints)foreach(var entry in endpoints){if(entry is not JsonObject endpoint||endpoint["address"] is not JsonValue value)continue;var host=value.ToString();if(!IPAddress.TryParse(host,out _)&&outbound["streamSettings"] is JsonObject stream){var security=stream["security"]?.ToString();if(security is "tls" or "reality"){var securityKey=security+"Settings";if(stream[securityKey] is not JsonObject)stream[securityKey]=new JsonObject();var options=stream[securityKey]!.AsObject();if(string.IsNullOrWhiteSpace(options["serverName"]?.ToString()))options["serverName"]=host;}}endpoint["address"]=await Resolve(host);}
   if(settings["peers"] is JsonArray peers)foreach(var entry in peers){if(entry is not JsonObject peer||peer["endpoint"] is not JsonValue value)continue;var endpoint=new Uri("udp://"+value);var ip=await Resolve(endpoint.Host.Trim('[',']'));peer["endpoint"]=(ip.Contains(':')?"["+ip+"]":ip)+":"+endpoint.Port;}
  }
  return(config,exclusions.ToArray());
 }
 static JsonObject TConfig(int port)=>JsonNode.Parse($$$"""
 {"log":{"level":"warn","timestamp":true},"dns":{"servers":[{"type":"tcp","tag":"remote","server":"1.1.1.1","detour":"proxy"}],"final":"remote"},"inbounds":[{"type":"tun","tag":"tun","interface_name":"MelavoTUN","address":["172.29.0.1/30","fdfe:dcba:9876::1/126"],"mtu":1400,"auto_route":true,"strict_route":true,"stack":"mixed","dns_mode":"hijack"}],"outbounds":[{"type":"socks","tag":"proxy","server":"127.0.0.1","server_port":{{{port}}},"version":"5"},{"type":"direct","tag":"direct"}],"route":{"auto_detect_interface":true,"rules":[{"process_name":["xray.exe"],"action":"route","outbound":"direct"},{"port":53,"action":"hijack-dns"}],"final":"proxy"}}
 """)!.AsObject();
 static string SafeError(string value){value=Regex.Replace(value,@"\x1B\[[0-9;]*m","");value=Regex.Replace(value,@"https?://[^\s]+","[URL]");value=Regex.Replace(value,@"[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}","[ID]");value=Regex.Replace(value,@"(?i)(privatekey|password|uuid|token|secret)\s*[:=]\s*\S+","$1=[hidden]");return value;}
 Process Spawn(string core,string file,params string[] args){var si=new ProcessStartInfo(Core(core)){UseShellExecute=false,CreateNoWindow=true,WorkingDirectory=Path.GetDirectoryName(Core(core)),RedirectStandardError=true,RedirectStandardOutput=true};foreach(var a in args)si.ArgumentList.Add(a);si.ArgumentList.Add("-c");si.ArgumentList.Add(file);var p=new Process{StartInfo=si};var queue=new ConcurrentQueue<string>();p.ErrorDataReceived+=(_,e)=>Capture(e.Data);p.OutputDataReceived+=(_,e)=>Capture(e.Data);void Capture(string? line){if(string.IsNullOrWhiteSpace(line))return;queue.Enqueue(SafeError(line));while(queue.Count>35)queue.TryDequeue(out _);}p.Start();logs[p.Id]=queue;p.BeginErrorReadLine();p.BeginOutputReadLine();return p;}
 string CoreError(Process? p){if(p==null)return "Engine did not start.";try{if(p.HasExited)p.WaitForExit();return Path.GetFileName(p.StartInfo.FileName)+Environment.NewLine+(logs.TryGetValue(p.Id,out var q)?string.Join(Environment.NewLine,q):"Engine exited without diagnostics");}catch{return "Engine stopped.";}}
 static async Task<bool> Probe(int? port){foreach(var endpoint in new[]{"https://www.gstatic.com/generate_204","https://www.cloudflare.com/cdn-cgi/trace"}){try{using var handler=new HttpClientHandler{UseProxy=port.HasValue};if(port.HasValue)handler.Proxy=new WebProxy($"socks5://127.0.0.1:{port}");using var http=new HttpClient(handler){Timeout=TimeSpan.FromSeconds(6)};using var r=await http.GetAsync(endpoint);if(r.IsSuccessStatusCode)return true;}catch{}}return false;}
 async Task Connect(){if(busy||updating||xray!=null)return;if(servers.SelectedIndices.Count==0){MessageBox.Show(L("Select a server first.","یک سرور انتخاب کنید."));return;}if(tun.Checked&&!new WindowsPrincipal(WindowsIdentity.GetCurrent()).IsInRole(WindowsBuiltInRole.Administrator)){MessageBox.Show(L("Run this app as administrator to use TUN.","برای TUN برنامه را با Run as administrator باز کنید."));return;}activeProfileKey=ProfileKey(Profiles[(int)servers.SelectedItems[0].Tag!]);busy=true;SetControls();details.Clear();string stage=L("Starting Xray","راه‌اندازی Xray");status.Text=stage+"…";logs.Clear();
  try{var l=new TcpListener(IPAddress.Loopback,0);l.Start();int port=((IPEndPoint)l.LocalEndpoint).Port;l.Stop();localProxyPort=port;session=Path.Combine(SubscriptionStore.DirectoryPath,"sessions",Guid.NewGuid().ToString("N"));Directory.CreateDirectory(session);var xc=Path.Combine(session,"xray.json");stage=L("Resolving server address","حل آدرس سرور");status.Text=stage+"…";var prepared=await Prepare(Profiles[(int)servers.SelectedItems[0].Tag!],port);File.WriteAllText(xc,prepared.Config.ToJsonString());stage=L("Starting Xray","راه‌اندازی Xray");xray=Spawn("xray.exe",xc,"run");job.Add(xray);bool ready=false;for(int i=0;i<50;i++){if(xray.HasExited)throw new Exception(CoreError(xray));try{using var s=new TcpClient();await s.ConnectAsync(IPAddress.Loopback,port);ready=true;break;}catch{await Task.Delay(100);}}if(!ready)throw new Exception("پورت محلی Xray آماده نشد.\n"+CoreError(xray));
   bool verified=false;if(tun.Checked){stage=L("Starting TUN","راه‌اندازی TUN");status.Text=stage+"…";var tc=Path.Combine(session,"tun.json");var tunConfig=TConfig(port);tunConfig["inbounds"]![0]!["route_exclude_address"]=new JsonArray(prepared.Exclusions.Select(x=>(JsonNode?)JsonValue.Create(x)).ToArray());File.WriteAllText(tc,tunConfig.ToJsonString());box=Spawn("sing-box.exe",tc,"run");job.Add(box);await Task.Delay(2500);if(box.HasExited)throw new Exception(CoreError(box));stage=L("Checking internet through TUN","بررسی اینترنت از TUN");status.Text=stage+"…";verified=await Probe(null);if(box.HasExited)throw new Exception(CoreError(box));}else{stage=L("Checking internet through SOCKS","بررسی اینترنت از SOCKS");status.Text=stage+"…";verified=await Probe(port);}if(xray.HasExited)throw new Exception(CoreError(xray));
   status.Text=(tun.Checked?L("TUN active","TUN فعال"):"SOCKS: 127.0.0.1:"+port)+(verified?L(" · Internet verified","؛ اینترنت بررسی شد"):L(" · Internet test did not respond","؛ پاسخ تست اینترنت دریافت نشد"));if(!verified)details.Text=L("The engines are running, but the internet test did not respond. Try opening a website or select another server.\r\n","هسته‌ها فعال‌اند، اما تست اینترنت پاسخی نداد. یک سایت را باز کنید؛ در صورت مشکل سرور دیگری انتخاب کنید.\r\n")+(box!=null?CoreError(box)+"\r\n":"")+CoreError(xray);
  }catch(Exception e){var error=stage+Environment.NewLine+SafeError(e.Message);Disconnect();status.Text=L("Connection failed at: ","اتصال ناموفق در مرحلهٔ ")+stage;details.Text=error;}finally{busy=false;SetControls();}}
 void Disconnect(){foreach(var p in new[]{box,xray}){if(p==null)continue;try{if(!p.HasExited){p.Kill(true);p.WaitForExit(4000);}}catch{}p.Dispose();}box=null;xray=null;if(session!=null){try{Directory.Delete(session,true);}catch{}session=null;}status.Text=L("Disconnected","قطع است");SetControls();}
 public static int Validate(string file){SubscriptionStore.SelfTest();var profiles=Parse(File.ReadAllText(file));var path=Path.Combine(Path.GetTempPath(),Guid.NewGuid()+".json");int errors=0;try{foreach(var c in profiles){var prepared=Prepare(c,17890).GetAwaiter().GetResult();File.WriteAllText(path,prepared.Config.ToJsonString());if(Check("xray.exe",path,"run","-test")!=0)errors++;var tc=TConfig(17890);tc["inbounds"]![0]!["route_exclude_address"]=new JsonArray(prepared.Exclusions.Select(x=>(JsonNode?)JsonValue.Create(x)).ToArray());File.WriteAllText(path,tc.ToJsonString());if(Check("sing-box.exe",path,"check")!=0)errors++;}File.WriteAllText(Path.Combine(AppContext.BaseDirectory,"validation.txt"),$"Profiles: {profiles.Count}; Xray and TUN config failures: {errors}; encrypted persistence roundtrip: passed");}finally{File.Delete(path);}return errors;}
 public static async Task<int> NetworkCheck(string file){var profiles=Parse(File.ReadAllText(file));var reports=new List<string>();int errors=0;using var job=new CoreJob();foreach(var index in new[]{0,5,10}.Where(i=>i<profiles.Count)){var path=Path.Combine(Path.GetTempPath(),Guid.NewGuid()+".json");Process? p=null;try{var listener=new TcpListener(IPAddress.Loopback,0);listener.Start();int port=((IPEndPoint)listener.LocalEndpoint).Port;listener.Stop();var prepared=await Prepare(profiles[index],port);File.WriteAllText(path,prepared.Config.ToJsonString());var si=new ProcessStartInfo(Core("xray.exe")){UseShellExecute=false,CreateNoWindow=true,WorkingDirectory=Path.GetDirectoryName(Core("xray.exe")),ArgumentList={"run","-c",path}};p=Process.Start(si)!;job.Add(p);await Task.Delay(700);bool ok=!p.HasExited&&await Probe(port);if(!ok)errors++;reports.Add($"Profile {index}: HTTPS through prepared SOCKS config = {ok}");}catch(Exception e){errors++;reports.Add($"Profile {index}: {SafeError(e.Message)}");}finally{if(p!=null){try{if(!p.HasExited){p.Kill(true);p.WaitForExit(4000);}}catch{}p.Dispose();}File.Delete(path);}}File.WriteAllLines(Path.Combine(AppContext.BaseDirectory,"network-check.txt"),reports);return errors;}
 static int Check(string core,string path,params string[] args){var info=new ProcessStartInfo(Core(core)){UseShellExecute=false,CreateNoWindow=true,WorkingDirectory=Path.GetDirectoryName(Core(core))};foreach(var a in args)info.ArgumentList.Add(a);info.ArgumentList.Add("-c");info.ArgumentList.Add(path);using var p=Process.Start(info)!;p.WaitForExit();return p.ExitCode;}
}
