using System.Diagnostics;
using System.Net;
using System.Net.Sockets;
using System.Text.Json.Nodes;
namespace MelavoClient;
sealed partial class Client {
 readonly CancellationTokenSource pingCancellation=new();bool pingTesting;readonly HashSet<string> latencyFailed=new();
 async Task CheckLatency(){if(preview){status.Text=L("Ping is unavailable in offline preview.","پینگ در پیش‌نمایش آفلاین اجرا نمی‌شود.");return;}if(servers.SelectedItems.Count==0||busy||updating||pingTesting)return;var profile=Profiles[(int)servers.SelectedItems[0].Tag!];var key=ProfileKey(profile);pingTesting=true;SetControls();status.Text=L("Measuring HTTPS through the selected tunnel…","اندازه‌گیری پاسخ HTTPS از تونل سرور انتخاب‌شده…");try{long ms=await MeasureProfile(profile,pingCancellation.Token);latency[key]=ms;latencyFailed.Remove(key);if(!IsDisposed){FillServers();status.Text=L($"Tunnel ping: {ms} ms · HTTPS response",$"پینگ تونل: {ms} ms · پاسخ HTTPS");}}catch(OperationCanceledException){}catch(Exception e){latency.Remove(key);latencyFailed.Add(key);if(!IsDisposed){FillServers();status.Text=L("Tunnel test did not respond; see About for diagnostics.","تست تونل پاسخ نداد؛ جزئیات در «درباره»");details.Text=L("Tunnel ping test: ","تست پینگ تونل: ")+SafeError(e.Message);}}finally{pingTesting=false;if(!IsDisposed)SetControls();}}
 static async Task<long> MeasureTunnel(int port,CancellationToken cancel){
  // Always proxy through the selected configuration. No direct fallback.
  var results=new List<long>();Exception? last=null;
  using var handler=new SocketsHttpHandler{UseProxy=true,Proxy=new WebProxy($"socks5://127.0.0.1:{port}"),ConnectTimeout=TimeSpan.FromSeconds(6),PooledConnectionLifetime=TimeSpan.Zero};using var http=new HttpClient(handler){Timeout=TimeSpan.FromSeconds(8)};
  foreach(var endpoint in new[]{"https://www.gstatic.com/generate_204","https://www.cloudflare.com/cdn-cgi/trace"}){
   for(int sample=0;sample<3;sample++){cancel.ThrowIfCancellationRequested();try{using var request=new HttpRequestMessage(HttpMethod.Get,endpoint);request.Headers.ConnectionClose=true;var watch=Stopwatch.StartNew();using var response=await http.SendAsync(request,HttpCompletionOption.ResponseHeadersRead,cancel);response.EnsureSuccessStatusCode();results.Add(Math.Max(1,watch.ElapsedMilliseconds));}catch(OperationCanceledException)when(cancel.IsCancellationRequested){throw;}catch(Exception e){last=e;if(results.Count==0)break;}}
   if(results.Count>0)break;
  }
  if(results.Count==0)throw new Exception("No HTTPS response was received through the tunnel.",last);return results.OrderBy(v=>v).ElementAt(results.Count/2);
 }
 static async Task<long> MeasureProfile(JsonObject profile,CancellationToken cancel){
  var path=Path.Combine(Path.GetTempPath(),"melavo-ping-"+Guid.NewGuid().ToString("N")+".json");Process? process=null;using var probeJob=new CoreJob();
  try{cancel.ThrowIfCancellationRequested();var listener=new TcpListener(IPAddress.Loopback,0);listener.Start();int port=((IPEndPoint)listener.LocalEndpoint).Port;listener.Stop();var prepared=await Prepare(profile,port);cancel.ThrowIfCancellationRequested();var outbound=Outbound(prepared.Config) as JsonObject??throw new Exception("The tunnel outbound is missing.");var tag=outbound["tag"]?.ToString();if(string.IsNullOrWhiteSpace(tag)){tag="melavo-latency";outbound["tag"]=tag;}var inboundTag=prepared.Config["inbounds"]![0]!["tag"]!.ToString();prepared.Config["routing"]=new JsonObject{["domainStrategy"]="AsIs",["rules"]=new JsonArray(new JsonObject{["type"]="field",["inboundTag"]=new JsonArray(inboundTag),["outboundTag"]=tag})};File.WriteAllText(path,prepared.Config.ToJsonString());var info=new ProcessStartInfo(Core("xray.exe")){UseShellExecute=false,CreateNoWindow=true,WorkingDirectory=Path.GetDirectoryName(Core("xray.exe")),RedirectStandardOutput=true,RedirectStandardError=true,ArgumentList={"run","-c",path}};process=Process.Start(info)!;probeJob.Add(process);var stdout=process.StandardOutput.ReadToEndAsync();var stderr=process.StandardError.ReadToEndAsync();bool ready=false;for(int i=0;i<50;i++){cancel.ThrowIfCancellationRequested();if(process.HasExited)throw new Exception("The tunnel test engine did not start.");try{using var socket=new TcpClient();await socket.ConnectAsync(IPAddress.Loopback,port,cancel);ready=true;break;}catch(SocketException){await Task.Delay(100,cancel);}}if(!ready)throw new Exception("The tunnel test port did not become ready.");return await MeasureTunnel(port,cancel);
  }finally{if(process!=null){try{if(!process.HasExited){process.Kill(true);await process.WaitForExitAsync();}}catch{}process.Dispose();}if(File.Exists(path))File.Delete(path);}
 }
 public static async Task<int> LatencyChecks(string file){var profiles=Parse(File.ReadAllText(file));var report=new List<string>();int failures=0;foreach(var protocol in new[]{"vless","vmess","wireguard"}){var profile=profiles.FirstOrDefault(p=>Outbound(p)?["protocol"]?.ToString()==protocol);if(profile==null)continue;try{var original=profile.ToJsonString();var ms=await MeasureProfile(profile,CancellationToken.None);if(original!=profile.ToJsonString())throw new Exception("Test modified original profile");report.Add($"PASS: {protocol} tunnel HTTPS median = {ms} ms");}catch(Exception e){failures++;report.Add($"FAIL: {protocol}: {SafeError(e.Message)}");}}var listener=new TcpListener(IPAddress.Loopback,0);listener.Start();int unusedPort=((IPEndPoint)listener.LocalEndpoint).Port;listener.Stop();try{await MeasureTunnel(unusedPort,CancellationToken.None);failures++;report.Add("FAIL: direct fallback detected");}catch{report.Add("PASS: unavailable proxy fails without direct fallback");}File.WriteAllLines(Path.Combine(AppContext.BaseDirectory,"latency-checks.txt"),report);return failures;}
}
