namespace MelavoClient;
sealed partial class Client {

 static void CheckSubscriptionActionBounds(Client client,Action<bool,string> assert){
  client.Opacity=0;client.ShowInTaskbar=false;client.Show();client.Navigate("Home");Application.DoEvents();
  foreach(var language in new[]{"en","fa"})foreach(var size in new[]{new Size(1380,1120),new Size(1240,780),new Size(1380,780)}){
   client.preferences.Language=language;client.ApplyLanguage();client.Size=size;client.PerformLayout();Application.DoEvents();
   foreach(var button in new[]{client.manageSubscription,client.refresh,client.editSubscription,client.deleteSubscription}){
    var bounds=button.RectangleToScreen(button.ClientRectangle);
    for(Control? parent=button.Parent;parent!=null&&parent is not Client;parent=parent.Parent){
     var interior=new Rectangle(parent.Padding.Left,parent.Padding.Top,parent.ClientSize.Width-parent.Padding.Horizontal,parent.ClientSize.Height-parent.Padding.Vertical);
     assert(parent.RectangleToScreen(interior).Contains(bounds),$"subscription action {button.Text} stays inside {parent.GetType().Name} at {size.Width}x{size.Height} ({language}): button={bounds}; parent={parent.RectangleToScreen(interior)}");
    }
    assert(button.Height>=36,"subscription action keeps usable height");
   }
  }
  client.preferences.Language="en";client.ApplyLanguage();client.Size=new(1380,1120);
 }
 static void CheckConfigurationMenu(Action<bool,string> assert){
  void Pump(int ms){var clock=System.Diagnostics.Stopwatch.StartNew();while(clock.ElapsedMilliseconds<ms){Application.DoEvents();Thread.Sleep(5);}}
  using var host=new Form{ShowInTaskbar=false,Size=new(500,500)};host.Show();using var menu=new ConfigurationMenu();int invoked=0;foreach(var glyph in new[]{"\uE72D","\uE70F","\uE74D","\uE9D9","\uE768"})menu.AddAction(glyph,()=>invoked++);
  foreach(var dark in new[]{true,false}){Design.Dark=dark;menu.Prepare("Germany · VLESS",false,new[]{"Connect","Share","Edit","Delete","Ping"},new[]{true,true,true,true,true});menu.Show(host,new Point(30,30));Pump(50);assert(menu.Opacity>0&&menu.Opacity<1,"configuration menu opens gradually");Pump(200);assert(menu.Region!=null&&!menu.Region.IsVisible(0,0),"configuration menu rounded geometry");using(var bitmap=new Bitmap(menu.Width,menu.Height)){menu.DrawToBitmap(bitmap,menu.ClientRectangle);bitmap.Save(Path.Combine(AppContext.BaseDirectory,dark?"review-config-menu-dark.png":"review-config-menu-light.png"));}menu.Close();assert(menu.Visible,"configuration menu closes gradually");Pump(220);assert(!menu.Visible,"configuration menu close finishes");}
  Design.Dark=true;menu.Prepare("کانفیگ",true,new[]{"اتصال","اشتراک‌گذاری","ویرایش","حذف","پینگ"},new[]{true,true,true,true,true});menu.Show(host,new Point(30,30));Pump(200);var card=((ToolStripControlHost)menu.Items[0]).Control;card.Controls.OfType<Button>().First().PerformClick();assert(invoked==0,"action waits for closing animation");Pump(230);assert(invoked==1&&!menu.Visible,"menu action runs once after closing");host.Close();
 }
 static void CheckTrafficRefresh(Client client,Action<bool,string> assert){
  using var process=System.Diagnostics.Process.GetCurrentProcess();client.preferences.Language="en";client.ApplyLanguage();client.xray=process;client.activeProfileKey=client.ProfileKey(client.Profiles[0]);
  try{client.SetControls();int titleChanges=0,hintChanges=0,speedChanges=0;client.stateTitle.TextChanged+=(_,_)=>titleChanges++;client.stateHint.TextChanged+=(_,_)=>hintChanges++;var label=client.metrics["download"][0];client.Metric("download","1 KB/s");label.TextChanged+=(_,_)=>speedChanges++;
   for(int i=0;i<40;i++){client.SyncUi();client.Metric("download","1 KB/s");}
   assert(titleChanges==0&&hintChanges==0&&speedChanges==0,"unchanged traffic ticks do not rewrite status or speed labels");
   for(int i=2;i<=41;i++){client.SyncUi();client.Metric("download",i+" KB/s");client.Metric("usage",i+" KB");}
   assert(speedChanges==40&&titleChanges==0&&hintChanges==0,"changing traffic only updates metric values");assert(label is StableLabel&&label.Parent is BufferedTable,"traffic values use buffered fixed geometry");
  }finally{client.xray=null;client.activeProfileKey=null;client.SetControls();}
 }
 static void CheckConfigFormats(Action<bool,string> assert){
  var json=Parse("{\"remarks\":\"Single config\",\"outbounds\":[{\"protocol\":\"freedom\"},{\"protocol\":\"vless\",\"settings\":{\"vnext\":[{\"address\":\"node.example\",\"port\":443,\"users\":[{\"id\":\"021f5c70-2ad6-4f88-b3f0-2f4f0e0a9bc1\"}]}]}}]}");assert(json.Count==1&&Outbound(json[0])?["protocol"]?.ToString()=="vless","single Xray JSON config");
  var uri="vless://021f5c70-2ad6-4f88-b3f0-2f4f0e0a9bc1@node.example:443?type=ws&security=tls&host=cdn.example&sni=cdn.example&path=%2Fv2ray#Fixture%20server";var link=Parse(uri);assert(link.Count==1&&link[0]["remarks"]?.ToString()=="Fixture server"&&Outbound(link[0])!["streamSettings"]?["wsSettings"]?["path"]?.ToString()=="/v2ray","single VLESS link conversion");
  assert(ShareText(link[0])==uri,"QR payload preserves complete original URI");
  var legacy=(System.Text.Json.Nodes.JsonObject)link[0].DeepClone();legacy["streamSettings"]=Outbound(legacy)!["streamSettings"]!.DeepClone();Outbound(legacy)!.AsObject().Remove("streamSettings");var snapshot=legacy.ToJsonString();var migrated=XConfig(legacy,1080);assert(legacy.ToJsonString()==snapshot&&migrated["streamSettings"]==null&&Outbound(migrated)?["streamSettings"]?["wsSettings"]?["path"]?.ToString()=="/v2ray","legacy transport migration preserves original profile");
  var invalidVmess="vmess://"+Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes("{\"add\":\"node.example\",\"port\":443,\"id\":\"invalid\"}"));try{ParseProxyLink(invalidVmess);assert(false,"malformed VMess UUID rejected");}catch(Exception error){assert(error.Message.Contains("identifier"),"malformed VMess UUID rejected");}
  var edited=(System.Text.Json.Nodes.JsonObject)link[0].DeepClone();Outbound(edited)!["streamSettings"]!["wsSettings"]!["path"]="/edited path";var exported=Parse(ShareText(edited))[0];assert(Outbound(exported)!["streamSettings"]?["wsSettings"]?["path"]?.ToString()=="/edited path"&&Outbound(exported)?["settings"]?["vnext"]?[0]?["users"]?[0]?["id"]?.ToString()=="021f5c70-2ad6-4f88-b3f0-2f4f0e0a9bc1","edited QR URI retains credentials and transport");
  var trojan="trojan://p%40ss%23word@node.example:443?type=grpc&serviceName=test&authority=cdn.example&security=tls&sni=cdn.example&alpn=h2#Trojan";assert(ShareText(Parse(trojan)[0])==trojan,"Trojan sharing preserves encoded password and all parameters");
  File.WriteAllBytes(Path.Combine(AppContext.BaseDirectory,"qr-fixture.png"),CreateQrPng(uri));
  var encoded=Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(uri+"\n"+uri.Replace("Fixture%20server","Second%20server")));var subscription=Parse(encoded);assert(subscription.Count==2&&subscription[1]["remarks"]?.ToString()=="Second server","base64 VLESS subscription");
  var vmessData=Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes("{\"ps\":\"VMess fixture\",\"add\":\"node.example\",\"port\":\"443\",\"id\":\"021f5c70-2ad6-4f88-b3f0-2f4f0e0a9bc1\",\"aid\":\"0\",\"scy\":\"auto\",\"net\":\"ws\",\"host\":\"cdn.example\",\"path\":\"/v2ray\",\"tls\":\"tls\"}"));var vmess=Parse("vmess://"+vmessData);assert(ShareText(vmess[0])=="vmess://"+vmessData,"VMess share preserves complete payload");assert(vmess.Count==1&&Outbound(vmess[0])?["protocol"]?.ToString()=="vmess","single VMess link conversion");
 }
 static void CheckEditorScrolling(Action<bool,string> assert){using var host=new Form{ShowInTaskbar=false,Opacity=0,Size=new(480,360)};var editor=new ModernInput{Dock=DockStyle.Fill,Multiline=true,ScrollBars=ScrollBars.Vertical,RightToLeft=RightToLeft.No,Font=new Font("Consolas",10),Text=string.Join("\r\n",Enumerable.Range(0,100).Select(i=>$"{{\"line\":{i}}}"))};host.Controls.Add(editor);host.Show();Application.DoEvents();assert(editor.ScrollMaximum>0,"multiline editor exposes scrolling");editor.ScrollToLine(55);Application.DoEvents();assert(editor.FirstVisibleLine>=50,"multiline editor scrollbar moves text");host.Close();}
  public static int UiChecks(){GlassAnimation.Capture=true;using var client=new Client(true);_ = client.Handle;client.LoadPreview();client.NormalizeTypography();void Assert(bool condition,string name){if(!condition)throw new Exception("UI regression: "+name);}CheckPremiumRendering(Assert);CheckConfigurationMenu(Assert);CheckConfigFormats(Assert);CheckEditorScrolling(Assert);CheckTrafficRefresh(client,Assert);
  var singleFixture=(System.Text.Json.Nodes.JsonObject)client.Profiles[0].DeepClone();client.SetConfigScope(true);Assert(client.groups.Items.Count==0&&client.servers.Items.Count==0,"single configuration tab is separate from subscriptions");client.AddSingleConfig(singleFixture);Assert(client.groups.Items.Count==1&&client.servers.Items.Count==1&&client.accountUsage.Text.Contains("1 single"),"single configuration tab shows local configurations");client.SetConfigScope(false);Assert(client.groups.Items.Count==1&&client.groups.SelectedItem is SubscriptionGroup subscription&&IsSubscription(subscription),"subscription tab excludes single configurations");
  client.preferences.Language="en";client.ApplyLanguage();client.search.Text="no-result";Assert(!Design.Persian(client.serverSummary.Text),"empty English selection hint");client.search.Clear();Assert(client.servers.SelectAt(new Point(30,70)),"right click hit selects configuration");Assert(!client.servers.SelectAt(new Point(30,5)),"header cannot open configuration menu");Assert(client.configMenu.ActionCount==5,"configuration menu has five actions");var autoGroup=(SubscriptionGroup)client.groups.SelectedItem!;Assert(client.SaveSubscriptionEdit(autoGroup,autoGroup.Name,autoGroup.Url,autoUpdate:false).GetAwaiter().GetResult()&&!client.subscriptions.First(IsSubscription).AutoUpdate,"automatic update can be disabled");autoGroup=client.subscriptions.First(IsSubscription);Assert(client.SaveSubscriptionEdit(autoGroup,autoGroup.Name,autoGroup.Url,autoUpdate:true).GetAwaiter().GetResult()&&client.subscriptions.First(IsSubscription).AutoUpdate,"automatic update can be enabled");var persisted=System.Text.Json.JsonSerializer.Deserialize<SubscriptionGroup>(System.Text.Json.JsonSerializer.Serialize(new SubscriptionGroup{AutoUpdate=false}));Assert(persisted!=null&&!persisted.AutoUpdate,"automatic update setting survives serialization");void EnglishOnly(Control c){if(c!=client.serverSummary&&c is not ModernInput&&c is not ModernSelect)Assert(!Design.Persian(c.Text),"English UI caption: "+c.GetType().Name+": "+c.Text);foreach(Control child in c.Controls)EnglishOnly(child);}EnglishOnly(client);using(var editDialog=client.CreateEditSubscriptionDialog((SubscriptionGroup)client.groups.SelectedItem!)){EnglishOnly(editDialog);}using(var addDialog=client.CreateSingleConfigDialog()){EnglishOnly(addDialog);Assert(addDialog.Controls[0].Controls.OfType<ModernInput>().Count()==1,"single configuration needs only its source");}using(var pasteDialog=client.CreateSubscriptionDialog("https://example.invalid/paste")){Assert(pasteDialog.Controls[0].Controls.OfType<ModernInput>().Any(input=>input.Text=="https://example.invalid/paste"),"subscription paste prefills URL");}Assert(client.editSubscription.Text=="Edit subscription","English subscription edit caption");
  void Pump(int milliseconds){var clock=System.Diagnostics.Stopwatch.StartNew();while(clock.ElapsedMilliseconds<milliseconds){Application.DoEvents();Thread.Sleep(5);}}using(var host=new Form{ShowInTaskbar=false,Opacity=0}){host.Show();using(var popup=new AnimatedDropDown()){popup.Items.Add("Subscription fixture");popup.Show(host,new Point(20,20));Pump(60);Assert(popup.Opacity>0&&popup.Opacity<1,"dropdown opens through intermediate opacity");Pump(180);popup.Close();Assert(popup.Visible,"dropdown close is animated");Pump(220);Assert(!popup.Visible,"dropdown close completes");}using(var dialog=new Form{ShowInTaskbar=false}){Motion.Dialog(dialog);dialog.Show(host);Pump(60);Assert(dialog.Opacity>0&&dialog.Opacity<1,"dialog animated opening");Pump(180);Assert(host.Controls.OfType<ModalBackdrop>().Count()==1,"modal background blur installed");dialog.Close();Pump(220);Assert(!host.Controls.OfType<ModalBackdrop>().Any(),"modal background blur removed after close");Assert(dialog.IsDisposed,"dialog animated close completes");}host.Close();}
  Assert(new UiPreferences().Language=="en"&&new UiPreferences().VisualStyle=="glass","premium English default");client.preferences.Language="en";client.ApplyLanguage();Assert(!client.metrics.ContainsKey("remaining")&&!client.metrics.ContainsKey("expiry"),"account metadata only beside traffic bar");Assert(client.pages.Count==3,"three pages");Assert(client.servers.Items.Count==3,"fixture servers");Assert(client.MaximizeBox&&client.MinimizeBox&&client.FormBorderStyle==FormBorderStyle.None&&client.titleBar!=null,"custom desktop window controls");Assert(!client.pages["Home"].AutoScroll&&!client.navigation.ContainsKey("Servers")&&!client.navigation.ContainsKey("Subscription"),"single home screen");client.search.Text="VMESS";Assert(client.servers.Items.Count==1,"protocol search");Assert((int)client.servers.Items[0].Tag! ==1,"filtered original profile mapping");client.servers.Items[0].Selected=true;client.Navigate("Home");Assert(client.metrics["protocol"][0].Text=="VMESS","dashboard selected protocol");client.ToggleFavorite();client.search.Clear();client.filter.SelectedIndex=1;Assert(client.servers.Items.Count==1,"favorite filter");client.filter.SelectedIndex=0;client.busy=true;client.SyncUi();Assert(client.power.State==ConnectionState.Connecting,"connecting state");client.busy=false;client.disconnecting=true;client.SyncUi();Assert(client.power.State==ConnectionState.Disconnecting,"disconnecting state");client.disconnecting=false;client.status.Text="اتصال ناموفق";client.SyncUi();Assert(client.power.State==ConnectionState.Error,"error state");client.status.Text="قطع است";client.SyncUi();Assert(client.power.State==ConnectionState.Disconnected,"disconnected state");Assert(client.accountProgress.Value==720,"subscription usage percent");
  foreach(var dark in new[]{false,true}){Design.Dark=dark;client.accountProgress.Value=0;Assert(client.accountProgress.FillColor==Design.Accent,"traffic zero color");client.accountProgress.Value=750;Assert(client.accountProgress.FillColor==Design.Warning,"traffic warning anchor");client.accountProgress.Value=1000;Assert(client.accountProgress.FillColor==Design.Error,"traffic full color");var previous=Design.Accent;for(int step=1;step<=1000;step++){client.accountProgress.Value=step;var color=client.accountProgress.FillColor;Assert(Math.Abs(color.R-previous.R)<=2&&Math.Abs(color.G-previous.G)<=2&&Math.Abs(color.B-previous.B)<=2,"continuous color interpolation");previous=color;}}client.UpdateAccount();
  using(var process=System.Diagnostics.Process.GetCurrentProcess()){try{client.activeProfileKey=client.ProfileKey(client.Profiles[0]);client.xray=process;client.SetControls();Assert(client.power.State==ConnectionState.Connected,"connected state");Assert(client.servers.Enabled&&client.search.Enabled&&client.filter.Enabled,"connected server browsing");var activeName=client.serverSummary.Text;client.FillServers();Assert(client.serverSummary.Text==activeName,"active name stable during list refresh");client.search.Text="no-match-fixture";Assert(client.serverSummary.Text==activeName,"active name stable with filtered empty list");client.search.Clear();client.servers.Items[1].Selected=true;client.UpdateSelectedSummary();Assert(client.metrics["protocol"][0].Text=="VLESS","connected dashboard stays on active server");Assert(!client.groups.Enabled&&!client.refresh.Enabled,"subscription mutation remains locked");client.busy=true;client.SetControls();Assert(client.servers.Enabled,"scroll remains enabled while connecting");}finally{client.busy=false;client.xray=null;client.activeProfileKey=null;client.SetControls();}}
  var fixtures=client.Profiles;for(int i=3;i<100;i++){var copy=(System.Text.Json.Nodes.JsonObject)fixtures[0].DeepClone();copy["remarks"]="Scroll fixture "+i;fixtures.Add(copy);}client.FillServers();client.servers.TopItem=client.servers.Items[60];int topBefore=(int)client.servers.TopItem!.Tag!;client.FillServers();Assert((int)client.servers.TopItem!.Tag! ==topBefore,"refresh preserves scroll position");client.servers.RestoreTop(20);Assert((int)client.servers.TopItem!.Tag! ==20,"scroll upward");client.servers.RestoreTop(65);Assert((int)client.servers.TopItem!.Tag! ==65,"scroll downward");client.servers.ScrollRows(3);Assert((int)client.servers.TopItem!.Tag! ==68,"wheel steps downward");client.servers.ScrollRows(-3);Assert((int)client.servers.TopItem!.Tag! ==65,"wheel steps upward");Assert(client.RightToLeft==RightToLeft.No&&client.url.RightToLeft!=RightToLeft.Yes,"RTL shell and technical URL");int smoothStart=client.servers.ScrollOffset;client.servers.QueueScroll(120);client.servers.AdvanceScroll();Assert(client.servers.ScrollOffset>smoothStart&&client.servers.ScrollOffset<smoothStart+120,"smooth wheel advances partially");int smoothMid=client.servers.ScrollOffset;client.FillServers();Assert(client.servers.ScrollOffset==smoothMid,"refresh preserves fractional scroll offset");client.preferences.Language="fa";client.ApplyLanguage();Assert(client.RightToLeft==RightToLeft.Yes&&client.servers.RightToLeft==RightToLeft.Yes&&client.search.RightToLeft==RightToLeft.Yes,"Persian RTL layout");Assert(client.metrics["protocol"][0].RightToLeft==RightToLeft.No,"technical metrics remain LTR");client.preferences.Language="en";client.ApplyLanguage();Assert(client.RightToLeft==RightToLeft.No&&client.navigation["Home"].Text=="Home","English LTR layout and labels");using(var dialog=client.CreateSubscriptionDialog()){dialog.CreateControl();dialog.PerformLayout();foreach(var input in dialog.Controls[0].Controls.OfType<ModernInput>()){input.CreateControl();input.PerformLayout();Assert(input.EditorBounds.Top>=0&&input.EditorBounds.Bottom<=input.Height,"input editor and caret fit container");}}Assert(client.servers is ServerList&&client.search is ModernInput&&client.groups is ModernSelect,"custom shared controls");Assert(client.servers.AccessibilityObject.GetChildCount()==100,"accessible server rows");client.servers.AccessibilityObject.GetChild(70)!.DoDefaultAction();Assert((int)client.servers.SelectedItems[0].Tag! ==70,"accessible selection mapping");using(var card=new Card{Size=new(100,100)}){Assert(card.Region!=null&&!card.Region.IsVisible(0,0)&&card.Region.IsVisible(50,50),"rounded child clipping");}
  using(var response=new HttpResponseMessage()){response.Headers.TryAddWithoutValidation("subscription-userinfo","upload=20; download=52; total=100; expire=1800000000");var list=ReadAccountHeader(response,new());var group=new SubscriptionGroup{Profiles=list};ApplyAccount(group);Assert(group.UsedBytes==72&&group.TotalBytes==100&&group.ExpiresUnix==1800000000,"subscription header extraction");}
  Design.Glass=false;var oldAccent=Design.Accent;client.preferences.VisualStyle="glass";Design.Glass=true;RefreshThemeGeometry(client);foreach(var glassDark in new[]{true,false}){Design.Dark=glassDark;client.ApplyTheme(client);Assert(Design.RadiusCard==26&&Design.Accent!=oldAccent,"glass theme uses distinct palette and geometry");using var image=new Bitmap(client.Width,client.Height);client.DrawToBitmap(image,new Rectangle(Point.Empty,client.Size));}Assert(System.Text.Json.JsonSerializer.Deserialize<UiPreferences>(System.Text.Json.JsonSerializer.Serialize(client.preferences))?.VisualStyle=="glass","visual style persists");client.preferences.VisualStyle="classic";Design.Glass=false;RefreshThemeGeometry(client);Design.Dark=true;client.ApplyTheme(client);
  var originalSize=client.Size;client.Size=new(1240,780);client.PerformLayout();var lastMetric=client.metrics["usage"][0];var position=client.PointToClient(lastMetric.PointToScreen(Point.Empty));Assert(position.Y+lastMetric.Height<=client.ClientSize.Height,"statistics fit at minimum window size");Assert(client.titleBar!.Top>=0 && client.titleBar.Right<=client.ClientSize.Width&&client.Controls.OfType<TableLayoutPanel>().First().Top>=client.titleBar.Bottom,"title bar and content have separate bounds");var subscriptionActions=new[]{client.manageSubscription,client.refresh,client.editSubscription,client.deleteSubscription};Assert(subscriptionActions.Select(b=>b.Height).Distinct().Count()==1,"subscription action heights are uniform");Assert(subscriptionActions.All(b=>b.Left>=0&&b.Right<=b.Parent!.ClientSize.Width),"subscription actions fit the minimum window width");Assert(client.groups.Height>=50,"subscription selector has generous height");Assert(client.groups.PointToScreen(Point.Empty).Y+client.groups.Height<=client.accountUsage.PointToScreen(Point.Empty).Y,"subscription hierarchy does not overlap");Assert(client.navigation["Home"].Parent!.Controls.OfType<BrandLockup>().Count()==1,"sidebar has vector brand lockup");client.Size=originalSize;
  for(int repeat=0;repeat<8;repeat++){client.Navigate("Settings");client.Navigate("Home");Application.DoEvents();}Assert(!client.pages.Values.Any(p=>p.Controls.OfType<TransitionCover>().Any()),"rapid navigation has no stale screenshot cover");foreach(var page in client.pages.Keys){client.Navigate(page);Assert(client.navigation[page].Selected&&client.navigation.Values.Count(n=>n.Selected)==1,"navigation "+page);}
  Design.Dark=false;client.ApplyTheme(client);Assert(client.BackColor==Design.Canvas,"light theme");Design.Dark=true;client.ApplyTheme(client);Assert(client.BackColor==Design.Canvas,"dark theme");client.CommitGroups(new(),null);client.SetConfigScope(false);client.SetControls();
  Assert(!client.refresh.Enabled&&!client.editSubscription.Enabled&&!client.deleteSubscription.Enabled&&!client.groups.Enabled,"empty subscription actions disabled");
  Assert(!client.pingAction!.Enabled&&!client.pingAllAction!.Enabled&&!client.publicIpAction!.Enabled&&!client.shareConfig.Enabled&&!client.editConfig.Enabled&&!client.favoriteAction!.Enabled,"empty server actions disabled");
  client.LoadPreview();client.SetControls();Assert(client.pingAllAction!.Enabled&&!client.publicIpAction!.Enabled,"ping all available with profiles; public IP requires connection");
  client.Size=client.MinimumSize;client.PerformLayout();Application.DoEvents();
  Assert(client.servers.Height>=120,"minimum window retains usable server table");
  Assert(TextRenderer.MeasureText("All servers",client.filter.Font).Width+46<=client.filter.Width,"minimum window filter caption fits");
  Assert(TextRenderer.MeasureText(client.search.PlaceholderText,client.search.Font).Width+24<=client.search.Width,"minimum window search hint fits");
  using(var edit=client.CreateEditSubscriptionDialog(client.subscriptions.First(IsSubscription))){edit.Show(client);Application.DoEvents();var save=edit.Controls[0].Controls.OfType<ModernButton>().Single();Assert(save.Height<=44&&save.Height>=34,"edit subscription save has standard height");edit.Close();}
  CheckSubscriptionActionBounds(client,Assert);
  client.job.Dispose();File.WriteAllText(Path.Combine(AppContext.BaseDirectory,"ui-checks.txt"),"PASS: navigation, search, favorites, active-server dashboard, enabled connected/connecting browsing, scroll preservation with 100 rows, upward/downward scroll, continuous traffic colors (1000 steps) in both themes, custom controls, English/Persian directions, smooth fractional scroll, stable active name, input geometry, connection/error states, account metadata, light/dark palettes. Preview fixtures only; no network or real subscription writes.");return 0;
 }
}
