using System.Diagnostics;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using QRCoder;
namespace MelavoClient;
sealed partial class Client {
 readonly ModernButton deleteSubscription=new(){Text="حذف",Kind=ButtonKind.Ghost};
 readonly ModernButton editSubscription=new(){Text="ویرایش ساب"};
 readonly ModernButton editConfig=new(){Text="ویرایش"};
 static bool IsSubscription(SubscriptionGroup group)=>Uri.TryCreate(group.Url,UriKind.Absolute,out var uri)&&uri.Scheme.Equals("https",StringComparison.OrdinalIgnoreCase);
 SubscriptionGroup? SingleConfigGroup=>subscriptions.FirstOrDefault(g=>!IsSubscription(g));
 void PopulateGroups(string? selected){
  var visible=subscriptions.Where(g=>singleConfigScope?!IsSubscription(g):IsSubscription(g)).ToArray();
  fillingServers=true;groups.SelectedIndex=-1;groups.Items.Clear();groups.Items.AddRange(visible.Cast<object>());
  var wanted=selected??(singleConfigScope?selectedSingleGroupId:selectedSubscriptionId);var index=Array.FindIndex(visible,g=>g.Id==wanted);
  if(index<0&&visible.Length>0)index=0;groups.SelectedIndex=index;fillingServers=false;
  if(groups.SelectedItem is SubscriptionGroup current){if(singleConfigScope)selectedSingleGroupId=current.Id;else selectedSubscriptionId=current.Id;}
  SyncConfigScope();groups.Invalidate();FillServers();UpdateSelectedSummary();
 }
 void SetConfigScope(bool single){if(singleConfigScope==single)return;if(groups.SelectedItem is SubscriptionGroup current){if(singleConfigScope)selectedSingleGroupId=current.Id;else selectedSubscriptionId=current.Id;}singleConfigScope=single;search.Clear();filter.SelectedIndex=0;PopulateGroups(single?selectedSingleGroupId:selectedSubscriptionId);if(!preview)Motion.Reveal(pages["Home"]);}
 void SyncConfigScope(){groups.Visible=!singleConfigScope;editSubscription.Text=L("Edit subscription","ویرایش ساب");subscriptionsTab.Text=L("Subscriptions","ساب‌ها");singleConfigsTab.Text=L("Single configurations","کانفیگ‌های تکی");shareConfig.Text=L("Share","اشتراک‌گذاری");subscriptionsTab.Selected=!singleConfigScope;subscriptionsTab.Primary=!singleConfigScope;singleConfigsTab.Selected=singleConfigScope;singleConfigsTab.Primary=singleConfigScope;manageSubscription.Text=singleConfigScope?L("Add config","افزودن کانفیگ"):L("Add subscription","افزودن ساب");refresh.Visible=!singleConfigScope;editSubscription.Visible=!singleConfigScope;deleteSubscription.Text=singleConfigScope?L("Remove config","حذف کانفیگ"):L("Remove","حذف");deleteSubscription.Enabled=groups.SelectedItem is SubscriptionGroup;editSubscription.Enabled=groups.SelectedItem is SubscriptionGroup;shareConfig.Enabled=servers.SelectedItems.Count>0;UpdateAccount();}
 static SubscriptionGroup CloneGroup(SubscriptionGroup g)=>JsonSerializer.Deserialize<SubscriptionGroup>(JsonSerializer.Serialize(g))!;
 static string SourceKey(JsonObject p){
  // Name changes at the provider must not discard the customer's local edit.
  JsonNode? Canonical(JsonNode? node)=>node switch{JsonObject o=>new JsonObject(o.OrderBy(x=>x.Key,StringComparer.Ordinal).Select(x=>new KeyValuePair<string,JsonNode?>(x.Key,Canonical(x.Value)))),JsonArray a=>new JsonArray(a.Select(Canonical).ToArray()),_=>node?.DeepClone()};
  return Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(Canonical(p["outbounds"])!.ToJsonString())));
 }
 static void ApplyOverrides(SubscriptionGroup g){if(g.SourceProfiles.Count==0)g.SourceProfiles=g.Profiles.Select(x=>(JsonObject)x.DeepClone()).ToList();g.Profiles=g.SourceProfiles.Select(p=>g.Overrides.TryGetValue(SourceKey(p),out var edited)?(JsonObject)edited.DeepClone():(JsonObject)p.DeepClone()).ToList();}
 void CommitGroups(List<SubscriptionGroup> candidate,string? selected){
  if(!preview)SubscriptionStore.Save(candidate); // Complete atomic persistence before replacing visible state.
  subscriptions=candidate;PopulateGroups(selected);SetControls();
 }
 void AddSingleConfig(JsonObject config,bool reportErrors=true){
  if(busy||updating||pingTesting||xray!=null)return;var group=SingleConfigGroup is { } existing?CloneGroup(existing):new SubscriptionGroup{Name=L("Single configurations","کانفیگ‌های تکی")};
  if(group.SourceProfiles.Count==0)group.SourceProfiles=group.Profiles.Select(p=>(JsonObject)p.DeepClone()).ToList();group.SourceProfiles.Add((JsonObject)config.DeepClone());ApplyOverrides(group);var candidate=subscriptions.Where(g=>IsSubscription(g)||g.Id!=group.Id).Append(group).ToList();
  singleConfigScope=true;try{CommitGroups(candidate,group.Id);status.Text=L("Configuration saved.","کانفیگ ذخیره شد.");}catch(Exception e){if(!reportErrors)throw;MessageBox.Show(this,SafeError(e.Message),L("Could not save changes","ذخیره تغییرات انجام نشد"));}
 }
 async Task<bool> AddSubscription(string title,string address,Action<string>? feedback=null,Func<string,Task<List<JsonObject>>>? fetcher=null){
  if(busy||updating||pingTesting||xray!=null)return false;
  address=address.Trim();if(!Uri.TryCreate(address,UriKind.Absolute,out var uri)||uri.Scheme!="https"){feedback?.Invoke(L("Enter a valid HTTPS subscription URL.","لینک معتبر HTTPS وارد کنید."));return false;}
  if(subscriptions.Any(g=>g.Url==address)){feedback?.Invoke(L("This subscription is already added. Select it and click Update.","این اشتراک قبلاً اضافه شده؛ آن را انتخاب و به‌روزرسانی کنید."));return false;}
  updating=true;SetControls();feedback?.Invoke(L("Downloading subscription…","در حال دریافت اشتراک…"));
  try{var profiles=await (fetcher??Fetch)(address);var g=new SubscriptionGroup{Name=string.IsNullOrWhiteSpace(title)?$"Subscription {subscriptions.Count+1}":title.Trim(),Url=address,Profiles=profiles,Updated=DateTime.UtcNow};ApplyAccount(g);ApplyOverrides(g);CommitGroups(subscriptions.Append(g).ToList(),g.Id);status.Text=L($"Subscription saved · {profiles.Count} servers",$"اشتراک ذخیره شد · {profiles.Count} سرور");return true;}
  catch(Exception e){var message=L("Could not add subscription: ","افزودن اشتراک انجام نشد: ")+SafeError(e.Message);feedback?.Invoke(message);status.Text=message;details.Text=message;return false;}
  finally{updating=false;SetControls();}
 }
 Form CreateSubscriptionDialog(string initialUrl=""){
  var dialog=new Form{Text=L("Add subscription","افزودن اشتراک"),ClientSize=new(580,360),AutoScaleMode=AutoScaleMode.None,FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false,StartPosition=FormStartPosition.CenterParent,Font=Design.Font(),RightToLeft=Fa?RightToLeft.Yes:RightToLeft.No};
  var form=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new(24),ColumnCount=1,RowCount=7};foreach(var h in new[]{32,44,32,44,64,42,-1})form.RowStyles.Add(h<0?new(SizeType.Percent,100):new(SizeType.Absolute,h));
  var title=new ModernInput{Dock=DockStyle.Fill,PlaceholderText=L("e.g. My subscription","مثلاً اشتراک من"),RightToLeft=dialog.RightToLeft,Font=Design.Font(10)};
  var address=new ModernInput{Dock=DockStyle.Fill,Text=initialUrl,PlaceholderText="https://…",RightToLeft=RightToLeft.No,Font=Design.Font(10)};
  var message=Design.Label(L("Paste the subscription link provided by your seller.","لینک اشتراک دریافتی از فروشنده را وارد کنید."),9,true);message.AutoSize=false;message.Dock=DockStyle.Fill;
  var save=new ModernButton{Text=L("Add subscription","افزودن اشتراک"),Primary=true,Dock=DockStyle.Fill};
  form.Controls.Add(Design.Label(L("Subscription name","نام اشتراک"),10),0,0);form.Controls.Add(title,0,1);form.Controls.Add(Design.Label(L("Subscription URL","لینک اشتراک"),10),0,2);form.Controls.Add(address,0,3);form.Controls.Add(message,0,4);form.Controls.Add(save,0,5);foreach(var label in form.Controls.OfType<Label>()){label.AutoSize=false;label.Dock=DockStyle.Fill;label.Margin=Padding.Empty;}dialog.Controls.Add(form);
  save.Click+=async(_,_)=>{if(string.IsNullOrWhiteSpace(title.Text)){message.Text=L("Enter a subscription name.","نام ساب را وارد کنید.");title.FocusEditor();return;}save.Enabled=title.Enabled=address.Enabled=false;try{if(await AddSubscription(title.Text,address.Text,text=>{message.Text=text;message.ForeColor=Design.Error;})){dialog.DialogResult=DialogResult.OK;dialog.Close();}}finally{if(!dialog.IsDisposed){save.Enabled=title.Enabled=address.Enabled=true;}}};
  dialog.FormClosing+=(_,e)=>{if(updating)e.Cancel=true;};dialog.Shown+=(_,_)=>title.FocusEditor();TranslateTree(dialog);ApplyTheme(dialog);Motion.Dialog(dialog);return dialog;
 }
 void ShowSubscriptionDialog(){if(busy||updating||pingTesting||xray!=null)return;using var dialog=CreateSubscriptionDialog();dialog.ShowDialog(this);}
 Form CreateEditSubscriptionDialog(SubscriptionGroup group){
  var dialog=new Form{Text=L("Edit subscription","ویرایش ساب"),ClientSize=new(580,420),AutoScaleMode=AutoScaleMode.None,FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false,StartPosition=FormStartPosition.CenterParent,Font=Design.Font(),RightToLeft=Fa?RightToLeft.Yes:RightToLeft.No};
  var form=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new(24),ColumnCount=1,RowCount=8};foreach(var h in new[]{32,44,32,44,64,54,42})form.RowStyles.Add(new(SizeType.Absolute,h));form.RowStyles.Add(new(SizeType.Percent,100));
  var title=new ModernInput{Dock=DockStyle.Fill,Text=group.Name,PlaceholderText=L("Subscription name","نام ساب"),RightToLeft=dialog.RightToLeft,Font=Design.Font(10)};
  var address=new ModernInput{Dock=DockStyle.Fill,Text=group.Url,RightToLeft=RightToLeft.No,Font=Design.Font(10)};
  var message=Design.Label(L("Changing the URL downloads the new subscription before saving.","با تغییر لینک، ساب جدید پیش از ذخیره دریافت می‌شود."),9,true);message.AutoSize=false;message.Dock=DockStyle.Fill;
  var autoUpdate=new ModernToggle{Text=L("Auto update · startup and hourly","به‌روزرسانی خودکار · هنگام اجرا و هر ساعت"),Checked=group.AutoUpdate,Dock=DockStyle.Fill};
  var save=new ModernButton{Text=L("Save changes","ذخیرهٔ تغییرات"),Primary=true,Dock=DockStyle.Fill};form.Controls.Add(Design.Label(L("Subscription name","نام ساب"),10),0,0);form.Controls.Add(title,0,1);form.Controls.Add(Design.Label(L("Subscription URL","لینک ساب"),10),0,2);form.Controls.Add(address,0,3);form.Controls.Add(message,0,4);form.Controls.Add(autoUpdate,0,5);form.Controls.Add(save,0,6);foreach(var label in form.Controls.OfType<Label>()){label.AutoSize=false;label.Dock=DockStyle.Fill;label.Margin=Padding.Empty;}dialog.Controls.Add(form);
  save.Click+=async(_,_)=>{save.Enabled=title.Enabled=address.Enabled=false;try{if(await SaveSubscriptionEdit(group,title.Text,address.Text,text=>{message.Text=text;message.ForeColor=Design.Error;},autoUpdate:autoUpdate.Checked)){dialog.DialogResult=DialogResult.OK;dialog.Close();}}finally{if(!dialog.IsDisposed)save.Enabled=title.Enabled=address.Enabled=true;}};
  dialog.FormClosing+=(_,e)=>{if(updating)e.Cancel=true;};dialog.Shown+=(_,_)=>title.FocusEditor();TranslateTree(dialog);ApplyTheme(dialog);Motion.Dialog(dialog);return dialog;
 }
 async Task<bool> SaveSubscriptionEdit(SubscriptionGroup original,string title,string address,Action<string>? feedback=null,Func<string,Task<List<JsonObject>>>? fetcher=null,bool? autoUpdate=null){
  if(busy||updating||pingTesting||xray!=null)return false;title=title.Trim();address=address.Trim();
  if(title.Length==0){feedback?.Invoke(L("Enter a subscription name.","نام ساب را وارد کنید."));return false;}
  if(!Uri.TryCreate(address,UriKind.Absolute,out var uri)||uri.Scheme!="https"){feedback?.Invoke(L("Enter a valid HTTPS subscription URL.","لینک معتبر HTTPS وارد کنید."));return false;}
  if(subscriptions.Any(g=>g.Id!=original.Id&&g.Url.Equals(address,StringComparison.OrdinalIgnoreCase))){feedback?.Invoke(L("This subscription is already added.","این ساب قبلاً اضافه شده است."));return false;}
  updating=true;SetControls();try{var candidate=CloneGroup(original);candidate.Name=title;candidate.AutoUpdate=autoUpdate??original.AutoUpdate;if(!candidate.Url.Equals(address,StringComparison.OrdinalIgnoreCase)){feedback?.Invoke(L("Downloading subscription…","در حال دریافت ساب…"));var profiles=await(fetcher??Fetch)(address);candidate.Url=address;candidate.Profiles=profiles;candidate.SourceProfiles=profiles.Select(p=>(JsonObject)p.DeepClone()).ToList();candidate.Overrides.Clear();candidate.Updated=DateTime.UtcNow;ApplyAccount(candidate);}CommitGroups(subscriptions.Select(g=>g.Id==candidate.Id?candidate:g).ToList(),candidate.Id);status.Text=L("Subscription updated.","ساب ویرایش شد.");return true;}
  catch(Exception e){feedback?.Invoke(L("Could not save subscription: ","ذخیرهٔ ساب انجام نشد: ")+SafeError(e.Message));return false;}finally{updating=false;SetControls();}
 }
 void ShowEditSubscriptionDialog(){if(busy||updating||pingTesting||xray!=null||groups.SelectedItem is not SubscriptionGroup group||!IsSubscription(group))return;using var dialog=CreateEditSubscriptionDialog(group);dialog.ShowDialog(this);}
 void DeleteSubscription(){if(busy||updating||pingTesting||xray!=null||groups.SelectedItem is not SubscriptionGroup g)return;
  if(singleConfigScope){DeleteSingleConfig(g);return;}
  if(MessageBox.Show(this,L($"Remove ‘{g.Name}’ and its servers?",$"اشتراک «{g.Name}» و سرورهای آن حذف شود؟"),L("Remove subscription","حذف اشتراک"),MessageBoxButtons.YesNo,MessageBoxIcon.Question)!=DialogResult.Yes)return;
  try{CommitGroups(subscriptions.Where(x=>x.Id!=g.Id).ToList(),null);status.Text=L("Subscription removed.","اشتراک حذف شد.");}catch(Exception e){MessageBox.Show(this,SafeError(e.Message),L("Could not save changes","ذخیره تغییرات انجام نشد"));}
 }
 void DeleteSingleConfig(SubscriptionGroup group,bool confirmed=false){if(servers.SelectedItems.Count==0)return;var index=(int)servers.SelectedItems[0].Tag!;var name=group.Profiles[index]["remarks"]?.ToString()??L("configuration","کانفیگ");if(!confirmed&&MessageBox.Show(this,L($"Remove ‘{name}’?",$"کانفیگ «{name}» حذف شود؟"),L("Remove configuration","حذف کانفیگ"),MessageBoxButtons.YesNo,MessageBoxIcon.Question)!=DialogResult.Yes)return;var candidate=CloneGroup(group);if(candidate.SourceProfiles.Count==0)candidate.SourceProfiles=candidate.Profiles.Select(p=>(JsonObject)p.DeepClone()).ToList();candidate.SourceProfiles.RemoveAt(index);candidate.Overrides.Remove(SourceKey(group.SourceProfiles.Count>index?group.SourceProfiles[index]:group.Profiles[index]));if(candidate.SourceProfiles.Count==0)CommitGroups(subscriptions.Where(g=>g.Id!=candidate.Id).ToList(),null);else{ApplyOverrides(candidate);CommitGroups(subscriptions.Select(g=>g.Id==candidate.Id?candidate:g).ToList(),candidate.Id);}}
 Form CreateSingleConfigDialog(string initialText=""){var dialog=new Form{Text=L("Add single configuration","افزودن کانفیگ تکی"),ClientSize=new(700,590),AutoScaleMode=AutoScaleMode.None,FormBorderStyle=FormBorderStyle.Sizable,MinimizeBox=false,StartPosition=FormStartPosition.CenterParent,Font=Design.Font(),RightToLeft=Fa?RightToLeft.Yes:RightToLeft.No};var grid=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new(20),ColumnCount=1,RowCount=3};grid.RowStyles.Add(new(SizeType.Absolute,34));grid.RowStyles.Add(new(SizeType.Percent,100));grid.RowStyles.Add(new(SizeType.Absolute,44));var source=new ModernInput{Dock=DockStyle.Fill,Text=initialText,Multiline=true,ScrollBars=ScrollBars.Vertical,RightToLeft=RightToLeft.No,Font=new Font("Consolas",10),PlaceholderText=L("Paste a configuration link or Xray JSON","یک لینک VLESS/VMess/Trojan یا JSON کانفیگ Xray را وارد کنید")};var hint=Design.Label(L("Each single configuration is stored separately from subscriptions.","هر کانفیگ تکی جدا از ساب‌ها نگهداری می‌شود."),9,true);hint.AutoSize=false;hint.Dock=DockStyle.Fill;var save=new ModernButton{Text=L("Validate & add","بررسی و افزودن"),Primary=true,Dock=DockStyle.Fill};grid.Controls.Add(hint,0,0);grid.Controls.Add(source,0,1);grid.Controls.Add(save,0,2);dialog.Controls.Add(grid);save.Click+=async(_,_)=>{save.Enabled=false;try{var profiles=Parse(source.Text);if(profiles.Count!=1)throw new Exception(L("Enter exactly one configuration.","فقط یک کانفیگ وارد کنید."));if(string.IsNullOrWhiteSpace(profiles[0]["remarks"]?.ToString()))profiles[0]["remarks"]=$"Config {SingleConfigGroup?.Profiles.Count+1??1}";await ValidateEdit(profiles[0]);AddSingleConfig(profiles[0]);dialog.DialogResult=DialogResult.OK;dialog.Close();}catch(Exception e){MessageBox.Show(dialog,SafeError(e.Message),L("Invalid configuration","کانفیگ نامعتبر است"),MessageBoxButtons.OK,MessageBoxIcon.Error);}finally{if(!dialog.IsDisposed)save.Enabled=true;}};TranslateTree(dialog);ApplyTheme(dialog);Motion.Dialog(dialog);return dialog;}
 void ShowSingleConfigDialog(){if(busy||updating||pingTesting||xray!=null)return;using var dialog=CreateSingleConfigDialog();dialog.ShowDialog(this);}
 async Task ValidateEdit(JsonObject config){
  if(config["outbounds"] is not JsonArray a||a.Count==0||Outbound(config)==null)throw new Exception(L("The configuration must contain a proxy outbound.","کانفیگ باید خروجی پروکسی داشته باشد."));
  var folder=SessionFiles.Create();var path=Path.Combine(folder,"edit.json");try{File.WriteAllText(path,XConfig(config,17890).ToJsonString());var info=new ProcessStartInfo(Core("xray.exe")){UseShellExecute=false,CreateNoWindow=true,WorkingDirectory=Path.GetDirectoryName(Core("xray.exe")),RedirectStandardError=true,RedirectStandardOutput=true,ArgumentList={"run","-test","-c",path}};using var process=CoreSecurity.Start(info);var output=process.StandardOutput.ReadToEndAsync();var error=process.StandardError.ReadToEndAsync();using var timeout=new CancellationTokenSource(TimeSpan.FromSeconds(10));try{await process.WaitForExitAsync(timeout.Token);}catch{if(!process.HasExited)process.Kill(true);throw;}var text=await output+await error;if(process.ExitCode!=0)throw new Exception(SafeError(text));}finally{SessionFiles.RemoveDirectory(folder);}
 }
 void SaveConfigEdit(SubscriptionGroup original,int index,JsonObject config){var candidate=CloneGroup(original);if(candidate.SourceProfiles.Count==0)candidate.SourceProfiles=candidate.Profiles.Select(x=>(JsonObject)x.DeepClone()).ToList();candidate.Overrides[SourceKey(candidate.SourceProfiles[index])]=(JsonObject)config.DeepClone();ApplyOverrides(candidate);CommitGroups(subscriptions.Select(g=>g.Id==candidate.Id?candidate:g).ToList(),candidate.Id);var row=servers.Items.FirstOrDefault(x=>x.Tag is int n&&n==index);if(row!=null)row.Selected=true;}
 async Task ShowConfigEditor(){
  if(busy||updating||pingTesting||xray!=null)return;if(groups.SelectedItem is not SubscriptionGroup group||servers.SelectedItems.Count==0){MessageBox.Show(this,L("Select a server first.","ابتدا یک سرور انتخاب کنید."));return;}int index=(int)servers.SelectedItems[0].Tag!;
  using var dialog=CreateConfigEditorDialog(group,index);dialog.ShowDialog(this);await Task.CompletedTask;
 }
 Form CreateConfigEditorDialog(SubscriptionGroup group,int index){
  var dialog=new Form{Text=L("Edit configuration","ویرایش کانفیگ"),ClientSize=new(820,640),AutoScaleMode=AutoScaleMode.None,FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false,StartPosition=FormStartPosition.CenterParent,Font=Design.Font(),RightToLeft=Fa?RightToLeft.Yes:RightToLeft.No};
  var grid=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new(20),ColumnCount=1,RowCount=5};foreach(var h in new[]{42,38,-1,56,42})grid.RowStyles.Add(h<0?new(SizeType.Percent,100):new(SizeType.Absolute,h));var title=new ModernInput{Dock=DockStyle.Fill,Text=group.Profiles[index]["remarks"]?.ToString()??"Server",PlaceholderText=L("Server name","نام سرور")};var hint=Design.Label(L("Advanced JSON editor. Local edits are kept when the source configuration is unchanged.","ویرایش پیشرفته JSON؛ تغییرات محلی با ثابت ماندن کانفیگ اصلی حفظ می‌شوند."),9,true);hint.AutoSize=false;hint.Dock=DockStyle.Fill;
  var json=new ModernInput{Dock=DockStyle.Fill,Multiline=true,ScrollBars=ScrollBars.Vertical,RightToLeft=RightToLeft.No,Text=group.Profiles[index].ToJsonString(new JsonSerializerOptions{WriteIndented=true}),Font=new Font("Consolas",10)};var feedback=Design.Label("",9,true);feedback.AutoSize=false;feedback.Dock=DockStyle.Fill;var save=new ModernButton{Text=L("Validate & save","بررسی و ذخیره"),Primary=true,Dock=DockStyle.Fill};grid.Controls.Add(title,0,0);grid.Controls.Add(hint,0,1);grid.Controls.Add(json,0,2);grid.Controls.Add(feedback,0,3);grid.Controls.Add(save,0,4);dialog.Controls.Add(grid);
  bool validating=false;dialog.FormClosing+=(_,e)=>{if(validating)e.Cancel=true;};save.Click+=async(_,_)=>{validating=true;save.Enabled=false;try{var config=JsonNode.Parse(json.Text)?.AsObject()??throw new Exception("Invalid JSON");config["remarks"]=title.Text.Trim();feedback.Text=L("Validating with Xray…","در حال بررسی با Xray…");await ValidateEdit(config);SaveConfigEdit(group,index,config);validating=false;dialog.Close();}catch(Exception e){feedback.Text=SafeError(e.Message);feedback.ForeColor=Design.Error;}finally{validating=false;if(!dialog.IsDisposed)save.Enabled=true;}};TranslateTree(dialog);ApplyTheme(dialog);Motion.Dialog(dialog);return dialog;
 }
 void ShowConfigShare(){
  if(groups.SelectedItem is not SubscriptionGroup group||servers.SelectedItems.Count==0)return;int index=(int)servers.SelectedItems[0].Tag!;if(index<0||index>=group.Profiles.Count)return;
  using var dialog=CreateConfigShareDialog(group,index);dialog.ShowDialog(this);
 }
 Form CreateConfigShareDialog(SubscriptionGroup group,int index){
  var text=ShareText(group.Profiles[index]);byte[]? png=null;string qrError="";
  try{png=CreateQrPng(text);}catch(Exception e){qrError=SafeError(e.Message);}
  var dialog=new Form{Text=L("Share configuration","اشتراک‌گذاری کانفیگ"),ClientSize=new(700,560),AutoScaleMode=AutoScaleMode.None,FormBorderStyle=FormBorderStyle.Sizable,MinimizeBox=false,StartPosition=FormStartPosition.CenterParent,Font=Design.Font(),RightToLeft=Fa?RightToLeft.Yes:RightToLeft.No};
  var layout=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new(18),ColumnCount=1,RowCount=3};layout.RowStyles.Add(new(SizeType.Absolute,36));layout.RowStyles.Add(new(SizeType.Percent,100));layout.RowStyles.Add(new(SizeType.Absolute,46));var heading=Design.Label(L("Share as text or QR code","ارسال متن یا کد QR"),12);heading.AutoSize=false;heading.Dock=DockStyle.Fill;layout.Controls.Add(heading,0,0);
  var body=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=1};body.ColumnStyles.Add(new(SizeType.Percent,50));body.ColumnStyles.Add(new(SizeType.Percent,50));var image=new PictureBox{Dock=DockStyle.Fill,SizeMode=PictureBoxSizeMode.Zoom,BackColor=Color.White,Margin=new(0,0,12,0)};var note=Design.Label(qrError.Length==0?L("Scan this QR code to import the configuration.","برای وارد کردن کانفیگ، این QR را اسکن کنید."):L("QR code could not be generated for this configuration.","ساخت QR برای این کانفیگ ممکن نشد.")+Environment.NewLine+qrError,9,true);note.Dock=DockStyle.Fill;note.TextAlign=ContentAlignment.MiddleCenter;
  if(png!=null){using var stream=new MemoryStream(png);using var sourceImage=new Bitmap(stream);image.Image=new Bitmap(sourceImage);body.Controls.Add(image,0,0);}else body.Controls.Add(note,0,0);var sharedText=new ModernInput{Dock=DockStyle.Fill,Multiline=true,WordWrap=true,ReadOnly=true,ScrollBars=ScrollBars.Vertical,RightToLeft=RightToLeft.No,Text=text,Font=new Font("Consolas",9)};body.Controls.Add(sharedText,1,0);layout.Controls.Add(body,0,1);
  var actions=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.RightToLeft,WrapContents=false};var copy=new ModernButton{Text=L("Copy text","کپی متن"),Primary=true,Width=120};var save=new ModernButton{Text=L("Save QR","ذخیره QR"),Width=120,Enabled=png!=null};var close=new ModernButton{Text=L("Close","بستن"),Width=100,Kind=ButtonKind.Ghost};actions.Controls.AddRange(new Control[]{close,save,copy});layout.Controls.Add(actions,0,2);dialog.Controls.Add(layout);
  copy.Click+=(_,_)=>{try{Clipboard.SetText(text);}catch(Exception e){MessageBox.Show(dialog,SafeError(e.Message),L("Clipboard unavailable","کلیپ‌بورد در دسترس نیست"),MessageBoxButtons.OK,MessageBoxIcon.Error);}};
  save.Click+=(_,_)=>{if(png==null)return;using var picker=new SaveFileDialog{Filter="PNG image (*.png)|*.png",FileName=ServerList.StripFlags(group.Profiles[index]["remarks"]?.ToString()??"configuration")+".png"};if(picker.ShowDialog(dialog)==DialogResult.OK)File.WriteAllBytes(picker.FileName,png);};close.Click+=(_,_)=>dialog.Close();dialog.FormClosed+=(_,_)=>image.Image?.Dispose();TranslateTree(dialog);ApplyTheme(dialog);Motion.Dialog(dialog);return dialog;
 }
 static byte[] CreateQrPng(string text){using var generator=new QRCodeGenerator();using var data=generator.CreateQrCode(text,QRCodeGenerator.ECCLevel.M);return new PngByteQRCode(data).GetGraphic(6);}
}
