using System.Diagnostics;
namespace MelavoClient;
sealed partial class Client {
 readonly ModernButton updateCore=new(){Text="آپدیت Xray",Width=170},updateApplication=new(){Text="آپدیت برنامه از ZIP",Width=220};
 readonly Label updateStatus=Design.Label("Xray از GitHub رسمی؛ برنامه از فایل نسخهٔ جدید",10,true);
 readonly Label installedInfo=Design.Label("Melavo 0.8.4\nXray / sing-box\nWindows 10 / 11 · x64\nEncrypted storage · Windows DPAPI",12);
 async Task LoadInstalledInfo(){if(preview)return;try{var x=await Task.Run(()=>UpdateService.CoreVersion(Core("xray.exe")));var s=await Task.Run(()=>UpdateService.CoreVersion(Core("sing-box.exe")));if(!IsDisposed)installedInfo.Text="Melavo "+UpdateService.AppVersion+"\n"+string.Join(" ",x.Split(' ',StringSplitOptions.RemoveEmptyEntries).Take(2))+"\n"+s+"\nWindows 10 / 11 · x64";}catch{}}
 void BuildUpdateCard(Panel stack){checkAppUpdate.Text=L("Check for updates","بررسی به‌روزرسانی");updateStatus.Text=L("Automatic updates from GitHub; local ZIP updates are also supported.","دریافت خودکار نسخهٔ جدید از گیت‌هاب؛ نصب از ZIP هم امکان‌پذیر است.");var card=AddCard(stack,210);var column=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false};column.Controls.Add(Design.Label("به‌روزرسانی",13));var buttons=new FlowLayoutPanel{Height=45,Width=760};buttons.Controls.AddRange(new Control[]{checkAppUpdate,updateCore,updateApplication});column.Controls.Add(buttons);updateStatus.MaximumSize=new(700,0);column.Controls.Add(updateStatus);card.Controls.Add(column);updateCore.Click+=async(_,_)=>await UpdateXray();updateApplication.Click+=async(_,_)=>await UpdateProgram();}
 bool CanUpdate(){if(preview){updateStatus.Text=L("Updates are unavailable in offline preview.","به‌روزرسانی در پیش‌نمایش آفلاین انجام نمی‌شود.");return false;}if(busy||updating||pingTesting||xray!=null||downloadingApp){updateStatus.Text=L("Disconnect before updating.","برای به‌روزرسانی، اتصال را قطع کنید.");return false;}return true;}
 async Task UpdateXray(){if(!CanUpdate())return;updating=true;SetControls();updateCore.Enabled=updateApplication.Enabled=false;try{updateStatus.Text=L("Checking official Xray releases…","بررسی نسخهٔ رسمی Xray…");var latest=await UpdateService.LatestCore();var installed=await Task.Run(()=>UpdateService.CoreVersion(Core("xray.exe")));var currentVersion=installed.Split(' ',StringSplitOptions.RemoveEmptyEntries).Skip(1).FirstOrDefault();if(Version.TryParse(currentVersion,out var current)&&Version.TryParse(latest.Version,out var available)&&current>=available){updateStatus.Text=L("Xray is up to date: ","Xray به‌روز است: ")+installed;return;}if(MessageBox.Show(L($"Installed: {installed}\nLatest stable release: {latest.Version}\nDownload and install?",$"نسخهٔ نصب‌شده: {installed}\nنسخهٔ پایدار رسمی: {latest.Version}\nدانلود و نصب شود؟"),L("Update Xray","آپدیت Xray"),MessageBoxButtons.YesNo,MessageBoxIcon.Question)!=DialogResult.Yes)return;var progress=new Progress<int>(percent=>updateStatus.Text=L($"Downloading and verifying Xray · {percent}%",$"دانلود و بررسی Xray · {percent}%"));var candidate=await UpdateService.DownloadCore(latest,progress);updateStatus.Text=L("Checking compatibility with saved configurations…","بررسی سازگاری با کانفیگ‌های ذخیره‌شده…");foreach(var profile in subscriptions.SelectMany(s=>s.Profiles)){var file=Path.Combine(candidate,"compatibility.json");try{File.WriteAllText(file,XConfig(profile,17890).ToJsonString());await Task.Run(()=>{var info=new ProcessStartInfo(Path.Combine(candidate,"xray.exe")){UseShellExecute=false,CreateNoWindow=true,WorkingDirectory=candidate,RedirectStandardOutput=true,RedirectStandardError=true,ArgumentList={"run","-test","-c",file}};using var p=Process.Start(info)!;var output=p.StandardOutput.ReadToEndAsync();var error=p.StandardError.ReadToEndAsync();if(!p.WaitForExit(10000)){p.Kill(true);throw new Exception("The new engine test timed out.");}if(p.ExitCode!=0)throw new Exception("The new engine is incompatible with a saved configuration; the previous engine was kept.");});}finally{File.Delete(file);}}
   await Task.Run(()=>UpdateService.ApplyCore(candidate,Path.Combine(AppContext.BaseDirectory,"core")));await LoadInstalledInfo();updateStatus.Text=L("Xray installed: "+latest.Version+" · Previous version backed up.","Xray نصب شد: "+latest.Version+" · نسخهٔ قبلی پشتیبان‌گیری شد.");
  }catch(Exception e){updateStatus.Text=L("Xray update failed: ","آپدیت Xray انجام نشد: ")+SafeError(e.Message);}finally{updating=false;SetControls();updateCore.Enabled=updateApplication.Enabled=true;}}
 async Task UpdateProgram(){if(!CanUpdate())return;using var dialog=new OpenFileDialog{Filter="Melavo release (*.zip)|*.zip",Title=L("Select a new Melavo release ZIP","فایل ZIP نسخهٔ جدید برنامه را انتخاب کنید")};if(dialog.ShowDialog(this)!=DialogResult.OK)return;updating=true;SetControls();updateCore.Enabled=updateApplication.Enabled=false;try{updateStatus.Text=L("Checking update package…","بررسی بستهٔ آپدیت…");var plan=await Task.Run(()=>UpdateService.PreparePackage(dialog.FileName));if(MessageBox.Show(L($"New version: {plan.Version}\nThe app will close and install this release. Subscriptions will be kept.\nFile: {Path.GetFileName(dialog.FileName)}\nContinue?",$"نسخهٔ جدید: {plan.Version}\nبرنامه بسته و نسخهٔ انتخاب‌شده نصب می‌شود. ساب‌ها حفظ می‌شوند.\nفایل انتخاب‌شده: {Path.GetFileName(dialog.FileName)}\nادامه؟"),L("Update app","آپدیت برنامه"),MessageBoxButtons.YesNo,MessageBoxIcon.Question)!=DialogResult.Yes)return;UpdateService.StartPackageInstall(plan,AppContext.BaseDirectory);updating=false;Close();}catch(Exception e){updateStatus.Text=L("App update failed: ","آپدیت برنامه انجام نشد: ")+SafeError(e.Message);}finally{updating=false;if(!IsDisposed){SetControls();updateCore.Enabled=updateApplication.Enabled=true;}}}
}




