namespace MelavoClient;
sealed partial class Client {
 public static int RenderChecks(){GlassAnimation.Capture=true;using var client=new Client(true){ShowInTaskbar=false,Opacity=0};client.Show();Application.DoEvents();foreach(var language in new[]{"en","fa"}){client.preferences.Language=language;client.ApplyLanguage();foreach(var dark in new[]{false,true}){Design.Dark=dark;client.ApplyTheme(client);foreach(var page in new[]{"Home","Settings","About"}){client.Navigate(page);Application.DoEvents();using var bitmap=new Bitmap(client.Width,client.Height);client.DrawToBitmap(bitmap,new Rectangle(Point.Empty,client.Size));bitmap.Save(Path.Combine(AppContext.BaseDirectory,$"review-{page}-{language}-{(dark?"dark":"light")}.png"));}using var dialog=client.CreateSubscriptionDialog();dialog.Show(client);Application.DoEvents();using var image=new Bitmap(dialog.Width,dialog.Height);dialog.DrawToBitmap(image,new Rectangle(Point.Empty,dialog.Size));image.Save(Path.Combine(AppContext.BaseDirectory,$"review-add-{language}-{(dark?"dark":"light")}.png"));dialog.Close();}}
  client.preferences.Language="en";client.ApplyLanguage();Design.Dark=true;client.ApplyTheme(client);client.Navigate("Home");using(var modal=client.CreateSubscriptionDialog()){modal.Show(client);var watch=System.Diagnostics.Stopwatch.StartNew();while(watch.ElapsedMilliseconds<350){Application.DoEvents();Thread.Sleep(5);}using var preview=new Bitmap(client.Width,client.Height);var backdrop=client.Controls.OfType<ModalBackdrop>().Single();backdrop.DrawToBitmap(preview,new Rectangle(Point.Empty,backdrop.Size));preview.Save(Path.Combine(AppContext.BaseDirectory,"review-modal-backdrop.png"));modal.Close();watch.Restart();while(watch.ElapsedMilliseconds<250){Application.DoEvents();Thread.Sleep(5);}}
  foreach(var language in new[]{"en","fa"})foreach(var dark in new[]{false,true}){client.preferences.Language=language;client.preferences.VisualStyle="glass";Design.Glass=true;Design.Dark=dark;RefreshThemeGeometry(client);client.ApplyLanguage();client.ApplyTheme(client);client.Navigate("Home");if(client.groups.SelectedItem is SubscriptionGroup demo)demo.Name="My subscription";client.groups.Invalidate();Application.DoEvents();using var glassImage=new Bitmap(client.Width,client.Height);client.DrawToBitmap(glassImage,new Rectangle(Point.Empty,client.Size));glassImage.Save(Path.Combine(AppContext.BaseDirectory,$"review-glass-{language}-{(dark?"dark":"light")}.png"));}
  client.preferences.Language="en";Design.Glass=true;Design.Dark=true;client.ApplyLanguage();client.search.Text="no-result";Application.DoEvents();using(var emptyImage=new Bitmap(client.Width,client.Height)){client.DrawToBitmap(emptyImage,new Rectangle(Point.Empty,client.Size));emptyImage.Save(Path.Combine(AppContext.BaseDirectory,"review-premium-empty.png"));}client.search.Clear();client.CommitGroups(new(),null);client.SetConfigScope(false);Application.DoEvents();using(var blankImage=new Bitmap(client.Width,client.Height)){client.DrawToBitmap(blankImage,new Rectangle(Point.Empty,client.Size));blankImage.Save(Path.Combine(AppContext.BaseDirectory,"review-premium-customer.png"));}client.LoadPreview();
  Design.Glass=false;client.preferences.VisualStyle="classic";RefreshThemeGeometry(client);
  client.preferences.Language="en";client.ApplyLanguage();Design.Dark=true;client.ApplyTheme(client);client.Navigate("Home");var fixtures=client.Profiles;for(int i=3;i<24;i++){var copy=(System.Text.Json.Nodes.JsonObject)fixtures[0].DeepClone();copy["remarks"]=$"SCROLL_CLIP_SENTINEL_{i:D2}";fixtures.Add(copy);}client.FillServers();int row=Design.Scale(client.servers,36);client.servers.ScrollRows(6);client.servers.QueueScroll(row/2);for(int i=0;i<32;i++)client.servers.AdvanceScroll();Application.DoEvents();using(var bitmap=new Bitmap(client.Width,client.Height)){client.DrawToBitmap(bitmap,new Rectangle(Point.Empty,client.Size));bitmap.Save(Path.Combine(AppContext.BaseDirectory,"review-scroll-clip.png"));}client.Close();return 0;}
}
