using System.Diagnostics;
using System.Net;
using System.Text.Json.Nodes;
namespace MelavoClient;
sealed partial class Client {
 public static async Task<int> HardeningChecks(string coreFolder){
  var report=new List<string>();void Assert(bool pass,string name){if(!pass)throw new Exception("Hardening regression: "+name);report.Add("PASS: "+name);}
  var sandbox=Path.Combine(AppContext.BaseDirectory,"hardening-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(sandbox);var previous=SubscriptionStore.CheckDirectory;Process? engine=null;
  try{
   var exe=Path.Combine(coreFolder,"xray.exe");using(var checks=new DisposableFiles(CoreSecurity.LockAndVerify(exe))){bool denied=false;try{using var mutation=new FileStream(exe,FileMode.Open,FileAccess.Write,FileShare.ReadWrite);}catch(IOException){denied=true;}Assert(denied,"verified core remains locked against replacement");}
   var bad=Path.Combine(sandbox,"bad");Directory.CreateDirectory(bad);var altered=Path.Combine(bad,"xray.exe");File.Copy(exe,altered);using(var file=new FileStream(altered,FileMode.Open,FileAccess.ReadWrite)){file.Position=file.Length-1;int value=file.ReadByte();file.Position--;file.WriteByte((byte)(value^1));}
   bool rejected=false;try{using var process=CoreSecurity.Start(new ProcessStartInfo(altered){UseShellExecute=false,CreateNoWindow=true,ArgumentList={"version"}});}catch{rejected=true;}Assert(rejected,"tampered executable rejected before process start");
   var dll=Path.Combine(bad,"wintun.dll");File.Copy(Path.Combine(coreFolder,"wintun.dll"),dll);File.Copy(exe,altered,true);using(var file=new FileStream(dll,FileMode.Open,FileAccess.Write)){file.WriteByte(0);}rejected=false;try{using var process=CoreSecurity.Start(new ProcessStartInfo(altered){UseShellExecute=false,CreateNoWindow=true,ArgumentList={"version"}});}catch{rejected=true;}Assert(rejected,"tampered core DLL rejected before process start");
   Design.Glass=true;using(var normal=new Bitmap(200,44))using(var focused=new Bitmap(200,44)){using var shape=Design.Round(new RectangleF(.5f,.5f,199,43),Design.RadiusInput);using(var g=Graphics.FromImage(normal)){g.Clear(Design.Canvas);GlassMaterial.Input(g,new Rectangle(0,0,200,44),shape,0);}using(var g=Graphics.FromImage(focused)){g.Clear(Design.Canvas);GlassMaterial.Input(g,new Rectangle(0,0,200,44),shape,1);}Assert(Enumerable.Range(0,3).Any(y=>normal.GetPixel(100,y)!=focused.GetPixel(100,y))&&normal.GetPixel(100,20)==focused.GetPixel(100,20),"focus edge visible without changing input interior");}
   SubscriptionStore.CheckDirectory=Path.Combine(sandbox,"data");var stale=Path.Combine(SubscriptionStore.DirectoryPath,"sessions",Guid.NewGuid().ToString("N"));Directory.CreateDirectory(stale);File.WriteAllText(Path.Combine(stale,"xray.json"),"synthetic-secret");SessionFiles.CleanupStale();Assert(!Directory.Exists(stale),"startup removes stale secret session");
   Directory.CreateDirectory(stale);var lockedPath=Path.Combine(stale,"xray.json");File.WriteAllText(lockedPath,"fixture");using(var locked=new FileStream(lockedPath,FileMode.Open,FileAccess.Read,FileShare.None)){SessionFiles.CleanupStale();Assert(File.Exists(lockedPath),"locked session cleanup does not crash");}SessionFiles.CleanupStale();
   var workerStage=UpdateService.NewStage();var workerFile=Path.Combine(workerStage,"MelavoClient.exe");File.Copy(exe,workerFile);var workerTarget=Path.Combine(sandbox,"worker-target");Directory.CreateDirectory(workerTarget);File.WriteAllText(Path.Combine(workerTarget,"MelavoClient.exe"),"old fixture");Directory.CreateDirectory(Path.Combine(workerTarget,"data"));File.WriteAllText(Path.Combine(workerTarget,"data","keep.txt"),"preserve");
   var workerPlan=new PackagePlan("9.0.0",workerStage,new[]{"MelavoClient.exe"},new(){{"MelavoClient.exe",UpdateService.Hash(workerFile)}});
   var script=UpdateService.WorkerScript(workerPlan,workerTarget,int.MaxValue,false);var shell=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System),"WindowsPowerShell","v1.0","powershell.exe");
   using(var worker=Process.Start(new ProcessStartInfo(shell){UseShellExecute=false,CreateNoWindow=true,RedirectStandardError=true,ArgumentList={"-NoProfile","-NonInteractive","-EncodedCommand",Convert.ToBase64String(System.Text.Encoding.Unicode.GetBytes(script))}})!){var stderr=worker.StandardError.ReadToEndAsync();await worker.WaitForExitAsync();Assert(worker.ExitCode==0,"update worker completes: "+await stderr);}
   Assert(File.ReadAllText(Path.Combine(workerStage,"result.txt")).Trim()=="Update installed"&&!File.Exists(workerFile)&&!Directory.Exists(Path.Combine(workerStage,"backup-app"))&&File.ReadAllText(Path.Combine(workerTarget,"data","keep.txt"))=="preserve","worker cleans staging backup and preserves customer data: "+File.ReadAllText(Path.Combine(workerStage,"result.txt"))+"; staged="+File.Exists(workerFile)+"; backup="+Directory.Exists(Path.Combine(workerStage,"backup-app")));Assert(UpdateService.ReadResults().SequenceEqual(new[]{true})&&!Directory.Exists(workerStage),"successful update result consumed and removed");
   var update=UpdateService.NewStage();Directory.CreateDirectory(Path.Combine(update,"core"));File.Copy(exe,Path.Combine(update,"MelavoClient.exe"));File.WriteAllText(Path.Combine(update,"core","geoip.dat"),"new fixture");
   Directory.CreateDirectory(Path.Combine(workerTarget,"core"));var lockedTarget=Path.Combine(workerTarget,"core","geoip.dat");File.WriteAllText(lockedTarget,"old fixture");var oldExeHash=UpdateService.Hash(Path.Combine(workerTarget,"MelavoClient.exe"));
   using(var changed=new FileStream(Path.Combine(update,"MelavoClient.exe"),FileMode.Append,FileAccess.Write)){changed.WriteByte(42);}
   var failedPlan=new PackagePlan("9.0.0",update,new[]{"MelavoClient.exe","core/geoip.dat"},new(){{"MelavoClient.exe",UpdateService.Hash(Path.Combine(update,"MelavoClient.exe"))},{"core/geoip.dat",UpdateService.Hash(Path.Combine(update,"core","geoip.dat"))}});
   var failedScript=UpdateService.WorkerScript(failedPlan,workerTarget,int.MaxValue,false);
   using(var locked=new FileStream(lockedTarget,FileMode.Open,FileAccess.ReadWrite,FileShare.None))using(var worker=Process.Start(new ProcessStartInfo(shell){UseShellExecute=false,CreateNoWindow=true,RedirectStandardError=true,ArgumentList={"-NoProfile","-NonInteractive","-EncodedCommand",Convert.ToBase64String(System.Text.Encoding.Unicode.GetBytes(failedScript))}})!){var stderr=worker.StandardError.ReadToEndAsync();await worker.WaitForExitAsync();await stderr;}
   Assert(UpdateService.Hash(Path.Combine(workerTarget,"MelavoClient.exe"))==oldExeHash&&File.ReadAllText(lockedTarget)=="old fixture"&&!Directory.Exists(Path.Combine(update,"backup-app")),"failed app update rolls back and cleans temporary backup");
   var result=UpdateService.ReadResults();Assert(result.Count==1&&!result[0]&&!Directory.Exists(update),"failed update result read before cleanup");
   string vmess(JsonObject data)=>"vmess://"+Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(data.ToJsonString()));
   var input=new JsonObject{["add"]="localhost",["port"]=443,["id"]="021f5c70-2ad6-4f88-b3f0-2f4f0e0a9bc1",["net"]="tcp",["type"]="http",["host"]="cdn.example",["path"]="/a+b",["tls"]="tls",["sni"]="sni.example",["alpn"]="h2,http/1.1"};
   var parsed=ParseProxyLink(vmess(input));var stream=Outbound(parsed)!["streamSettings"]!;
   Assert(stream["tlsSettings"]?["alpn"]?.AsArray().Count==2&&stream["tlsSettings"]?["serverName"]?.ToString()=="sni.example"&&stream["tcpSettings"]?["header"]?["request"]?["path"]?[0]?.ToString()=="/a+b","VMess ALPN SNI and HTTP header preserved");
   input["net"]="grpc";input["serviceName"]="service+a";input["authority"]="grpc.example";input["multiMode"]=true;parsed=ParseProxyLink(vmess(input));stream=Outbound(parsed)!["streamSettings"]!;
   Assert(stream["grpcSettings"]?["serviceName"]?.ToString()=="service+a"&&stream["grpcSettings"]?["authority"]?.ToString()=="grpc.example"&&stream["grpcSettings"]?["multiMode"]?.GetValue<bool>()==true,"VMess gRPC parameters preserved");
   parsed["remarks"]="Edited fixture";var shared=ParseProxyLink(ShareText(parsed));Assert(Outbound(shared)?["streamSettings"]?["grpcSettings"]?.ToJsonString()==stream["grpcSettings"]?.ToJsonString(),"edited VMess share retains complete transport object");
   var link=ParseProxyLink("vless://021f5c70-2ad6-4f88-b3f0-2f4f0e0a9bc1@localhost:443?type=ws&path=/a+b");Assert(Outbound(link)?["streamSettings"]?["wsSettings"]?["path"]?.ToString()=="/a+b","URI literal plus preserved");
   var config=new JsonObject{["inbounds"]=new JsonArray(new JsonObject{["listen"]="127.0.0.1",["port"]=FreePort(),["protocol"]="socks",["settings"]=new JsonObject{["auth"]="noauth",["udp"]=true}}),["outbounds"]=new JsonArray(new JsonObject{["protocol"]="freedom"}),["log"]=new JsonObject{["loglevel"]="warning"}};
   var preserve=(JsonObject)config.DeepClone();preserve["inbounds"]![0]!["tag"]="original-socks";preserve["policy"]=new JsonObject{["levels"]=new JsonObject{["0"]=new JsonObject{["handshake"]=7}}};EnableStats(preserve,FreePort());Assert(preserve["inbounds"]![0]!["tag"]?.ToString()=="original-socks"&&preserve["policy"]?["levels"]?["0"]?["handshake"]?.GetValue<int>()==7,"statistics preserve existing routing tag and policy");int stats=FreePort();EnableStats(config,stats);var fileName=Path.Combine(sandbox,"stats.json");File.WriteAllText(fileName,config.ToJsonString());
   var info=new ProcessStartInfo(exe){UseShellExecute=false,CreateNoWindow=true,WorkingDirectory=coreFolder,RedirectStandardError=true,RedirectStandardOutput=true,ArgumentList={"run","-c",fileName}};
   engine=CoreSecurity.Start(info);using var testJob=new CoreJob();testJob.Add(engine);var errors=engine.StandardError.ReadToEndAsync();var output=engine.StandardOutput.ReadToEndAsync();
   bool ready=false;for(int i=0;i<40;i++){try{await QueryTraffic(stats);ready=true;break;}catch{if(engine.HasExited)throw new Exception("Stats engine exited: "+await errors);await Task.Delay(100);}}Assert(ready,"Xray statistics API is reachable");
   var before=await QueryTraffic(stats);int webPort=FreePort();using var web=new HttpListener();web.Prefixes.Add($"http://127.0.0.1:{webPort}/");web.Start();
   var serve=Task.Run(async()=>{var context=await web.GetContextAsync();var payload=new byte[32768];context.Response.ContentLength64=payload.Length;await context.Response.OutputStream.WriteAsync(payload);context.Response.Close();});
   using(var handler=new SocketsHttpHandler{UseProxy=true,Proxy=new WebProxy($"socks5://127.0.0.1:{config["inbounds"]![0]!["port"]}")})using(var http=new HttpClient(handler)){var bytes=await http.GetByteArrayAsync($"http://127.0.0.1:{webPort}/");Assert(bytes.Length==32768,"loopback download traverses SOCKS");}
   await serve;var after=await QueryTraffic(stats);Assert(after.Rx>before.Rx&&after.Tx>before.Tx,"SOCKS counters measure actual transfer without TUN");
   engine.Kill(true);await engine.WaitForExitAsync();engine.Dispose();engine=null;
   using(var client=new Client(true)){client.totalRx=client.totalTx=123;client.Metric("usage","246 B");client.ResetTraffic();Assert(client.totalRx==0&&client.totalTx==0&&client.metrics["usage"].All(x=>x.Text=="—"),"disconnect clears previous session metrics");}
   File.WriteAllLines(Path.Combine(AppContext.BaseDirectory,"hardening-checks.txt"),report);return 0;
  }finally{if(engine!=null){try{if(!engine.HasExited){engine.Kill(true);await engine.WaitForExitAsync();}}catch{}engine.Dispose();}SubscriptionStore.CheckDirectory=previous;if(Path.GetFullPath(sandbox).StartsWith(Path.GetFullPath(AppContext.BaseDirectory)+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase))Directory.Delete(sandbox,true);}
 }
 sealed class DisposableFiles(List<FileStream> files):IDisposable {public void Dispose(){foreach(var file in files)file.Dispose();}}
}
