using System.Diagnostics;
using System.Net.NetworkInformation;
using System.Net.Sockets;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json.Nodes;
namespace MelavoClient;
sealed partial class Client {
 readonly Label creatorCredit=Design.Label("",8,true);
 readonly LinkLabel creatorLink=new(){Text="github.com/sirvan1133",AutoSize=false,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleCenter,RightToLeft=RightToLeft.No,LinkBehavior=LinkBehavior.HoverUnderline,Font=Design.Font(8),Margin=Padding.Empty,TabStop=true,AccessibleName="GitHub: sirvan1133"};
 ModernButton? favoriteAction,pingAction,pingAllAction,publicIpAction;
 readonly UiPreferences preferences=UiPreferences.Read();
 readonly Dictionary<string,Panel> pages=new();readonly Dictionary<string,ModernButton> navigation=new();
 readonly Dictionary<string,List<Label>> metrics=new();readonly Dictionary<string,long> latency=new();
 readonly ModernInput search=new(){PlaceholderText="جستجوی نام، کشور یا پروتکل",Width=300};
 readonly ModernSelect filter=new(){DropDownStyle=ComboBoxStyle.DropDownList,Width=160};
 readonly PowerControl power=new();readonly Label stateTitle=Design.Label("Disconnected",19),stateHint=Design.Label("برای شروع، یک سرور انتخاب کنید",10,true),serverSummary=Design.Label("هیچ سروری انتخاب نشده",11);
 readonly ModernButton manageSubscription=new(){Text="افزودن اشتراک",Width=145,Primary=true};
 readonly QuietProgress accountProgress=new(){Maximum=1000,Height=8,Dock=DockStyle.Top};
 readonly Label accountUsage=Design.Label("اطلاعات حجم در ساب موجود نیست",15),accountExpiry=Design.Label("تاریخ انقضا نامشخص",10,true),groupDescription=Design.Label("گروه‌های شما با هر بار بازشدن خودکار آپدیت می‌شوند",10,true);
 readonly NotifyIcon tray=new(){Icon=SystemIcons.Shield,Text="Melavo VPN"};
 Panel? pageHost;string currentPage="Home";ConnectionState visualState;DateTime? connectedAt;long lastRx,lastTx,totalRx,totalTx;bool sampled,disconnecting;string? activeProfileKey;float animation;DateTime sampleAt;DateTime pageTransition;
 void BuildShell(){
  using(var iconStream=typeof(Client).Assembly.GetManifestResourceStream("MelavoClient.Assets.Melavo.ico")){if(iconStream!=null){Icon=new Icon(iconStream);tray.Icon=Icon;}}
  Design.Glass=preferences.VisualStyle=="glass";Design.Dark=preferences.Dark;Text="Melavo VPN · 0.8.11"+(SubscriptionStore.Edition=="customer"?" · Customer":"");Font=Design.Font();BackColor=Design.Canvas;ForeColor=Design.Text;RightToLeft=RightToLeft.Yes;Size=new(1380,1120);FormBorderStyle=FormBorderStyle.None;MaximizeBox=true;MinimizeBox=true;StartPosition=FormStartPosition.CenterScreen;
  var shell=new BufferedTable{Dock=DockStyle.Fill,ColumnCount=2,RowCount=1,Padding=new(18,12,18,18),RightToLeft=RightToLeft.No};shell.ColumnStyles.Add(new(SizeType.Percent,100));shell.ColumnStyles.Add(new(SizeType.Absolute,212));Controls.Add(shell);Padding=new(0,48,0,0);titleBar=new WindowTitleBar(this){Dock=DockStyle.None,Bounds=new Rectangle(0,0,ClientSize.Width,48),Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right};Controls.Add(titleBar);titleBar.BringToFront();
  var sidebar=new Card{RightToLeft=RightToLeft.Yes,Dock=DockStyle.Fill,Padding=new(18,22,18,18),BackColor=Design.Surface};shell.Controls.Add(sidebar,1,0);
  var nav=new BufferedFlow{Dock=DockStyle.Top,AutoSize=true,FlowDirection=FlowDirection.TopDown,WrapContents=false};nav.Controls.Add(new BrandLockup{Margin=new(0,0,0,20)});
  foreach(var item in new[]{("Home","◉  خانه"),("Settings","⚙  تنظیمات"),("About","ⓘ  درباره")}){var button=new ModernButton{Text=item.Item2[3..],IconGlyph=item.Item1 switch{"Home"=>"\uE80F","Servers"=>"\uE774","Subscription"=>"\uE8A5","Statistics"=>"\uE9D9","Settings"=>"\uE713",_=>"\uE946"},Width=176,Height=44,Margin=new(0,8,0,0),AccessibleName=item.Item1,Kind=ButtonKind.Ghost,RightToLeft=RightToLeft.Yes};var key=item.Item1;button.Click+=(_,_)=>Navigate(key);navigation[key]=button;nav.Controls.Add(button);}sidebar.Controls.Add(nav);
  var foot=Design.Label("VERSION 0.8.11\nXray + sing-box",7,true);foot.Dock=DockStyle.Fill;foot.AutoSize=false;foot.TextAlign=ContentAlignment.MiddleCenter;foot.Margin=Padding.Empty;
  var brandingFooter=new BufferedTable{Dock=DockStyle.Bottom,Height=100,ColumnCount=1,RowCount=3,Margin=Padding.Empty};foreach(var height in new[]{46,28,26})brandingFooter.RowStyles.Add(new(SizeType.Absolute,height));
  creatorCredit.Dock=DockStyle.Fill;creatorCredit.AutoSize=false;creatorCredit.Margin=Padding.Empty;creatorCredit.TextAlign=ContentAlignment.MiddleCenter;
  creatorLink.ForeColorChanged+=(_,_)=>{creatorLink.LinkColor=Design.Muted;creatorLink.ActiveLinkColor=Design.Accent;creatorLink.VisitedLinkColor=Design.Muted;creatorLink.RightToLeft=RightToLeft.No;};
  creatorLink.Links.Add(0,creatorLink.Text.Length,"https://github.com/sirvan1133");creatorLink.LinkClicked+=(_,_)=>{try{Process.Start(new ProcessStartInfo("https://github.com/sirvan1133"){UseShellExecute=true});}catch(Exception e){status.Text=SafeError(e.Message);}};
  brandingFooter.Controls.Add(foot,0,0);brandingFooter.Controls.Add(creatorCredit,0,1);brandingFooter.Controls.Add(creatorLink,0,2);sidebar.Controls.Add(brandingFooter);
  pageHost=new BufferedPanel{RightToLeft=RightToLeft.Yes,Dock=DockStyle.Fill,Padding=new(24,12,10,10)};shell.Controls.Add(pageHost,0,0);
  InitializeServerControls();BuildHome();BuildSettings();BuildAbout();
  var footer=new Panel{Dock=DockStyle.Bottom,Height=40,Padding=new(12,8,12,0)};status.Font=Design.Font(9);status.ForeColor=Design.Muted;footer.Controls.Add(status);pageHost.Controls.Add(footer);footer.BringToFront();
  search.TextChanged+=(_,_)=>FillServers();filter.SelectedIndexChanged+=(_,_)=>FillServers();servers.Resize+=(_,_)=>FitColumns();servers.SelectedIndexChanged+=(_,_)=>{if(!fillingServers)UpdateSelectedSummary();};servers.DoubleClick+=(_,_)=>{Navigate("Home");};
  power.Click+=async(_,_)=>{if(busy||updating||disconnecting||preview)return;if(xray==null){if(servers.SelectedItems.Count==0){Navigate("Home");status.Text=L("Please select a server first.","ابتدا یک سرور انتخاب کنید.");servers.Focus();return;}Navigate("Home");await Connect();}else{disconnecting=true;SyncUi();await Task.Delay(100);Disconnect();disconnecting=false;SyncUi();}};
  details.TextChanged+=(_,_)=>{if(details.Text.Length>0&&status.Text.Contains("ناموفق"))SyncUi();};
  Resize+=(_,_)=>{foreach(var p in pages.Values)FitPage(p);FitColumns();};
  var uiTimer=new System.Windows.Forms.Timer{Interval=33};uiTimer.Tick+=(_,_)=>{animation+=.04f;power.Phase=animation;if(pages.TryGetValue(currentPage,out var animatedPage)&&animatedPage.Controls.OfType<FlowLayoutPanel>().FirstOrDefault() is FlowLayoutPanel animatedStack){var elapsed=(DateTime.UtcNow-pageTransition).TotalMilliseconds;if(elapsed<150){int top=(int)(6*Math.Pow(1-elapsed/150,2));if(animatedStack.Padding.Top!=top)animatedStack.Padding=new Padding(0,top,8,0);}else if(animatedStack.Padding.Top!=0)animatedStack.Padding=new Padding(0,0,8,0);}if(power.Visible&&(Design.Glass||visualState is ConnectionState.Connecting or ConnectionState.Disconnecting))power.Invalidate();};uiTimer.Start();
  var monitor=new System.Windows.Forms.Timer{Interval=1000};monitor.Tick+=(_,_)=>{SyncUi();SampleTraffic();};monitor.Start();
  tray.ContextMenuStrip=new ContextMenuStrip();tray.ContextMenuStrip.Items.Add("بازکردن",null,(_,_)=>RestoreWindow());tray.ContextMenuStrip.Items.Add("قطع اتصال",null,(_,_)=>{if(!busy){Disconnect();SyncUi();}});tray.ContextMenuStrip.Items.Add("خروج",null,(_,_)=>{RestoreWindow();Close();});tray.DoubleClick+=(_,_)=>RestoreWindow();
  Resize+=(_,_)=>{if(WindowState==FormWindowState.Minimized&&preferences.Tray){tray.Visible=true;Hide();}};FormClosed+=(_,_)=>{uiTimer.Dispose();monitor.Dispose();tray.Dispose();};
  Shown+=async(_,_)=>await LoadInstalledInfo();HandleCreated+=(_,_)=>NativeTheme.Window(Handle);ApplyLanguage();ApplyTheme(this);Navigate("Home");SyncUi();
 }
 void NormalizeTypography(){void Reset(Control c){if(c.Tag is TextStyle t)c.Font=Design.Font(t.Size,t.Weight);else if(c is ModernButton)c.Font=Design.Font(Design.Glass?8:9);foreach(Control child in c.Controls)Reset(child);}Reset(this);if(stateTitle.Parent is TableLayoutPanel center&&center.Parent is Card hero&&hero.Tag?.ToString()!="fixed-home"){center.RowStyles[0].Height=power.Height+16;center.RowStyles[1].Height=stateTitle.GetPreferredSize(new Size(900,0)).Height+20;center.RowStyles[2].Height=stateHint.GetPreferredSize(new Size(900,0)).Height+20;center.RowStyles[3].SizeType=SizeType.Absolute;center.RowStyles[3].Height=serverSummary.GetPreferredSize(new Size(900,0)).Height+20;hero.Height=(int)center.RowStyles.Cast<RowStyle>().Sum(x=>x.Height)+hero.Padding.Vertical;}foreach(var values in metrics.Values)foreach(var label in values){label.Height=label.GetPreferredSize(new Size(400,0)).Height+12;if(label.Parent is Card card&&card.Parent is TableLayoutPanel grid){var heading=card.Controls.OfType<Label>().FirstOrDefault(l=>l!=label);grid.Height=Math.Max(grid.Height,card.Padding.Vertical+label.Height+(heading?.PreferredHeight??0)+18);}}foreach(var p in pages.Values)FitPage(p);}
 void RestoreWindow(){Show();WindowState=FormWindowState.Normal;Activate();tray.Visible=false;}
 void Navigate(string page){if(page is "Servers" or "Subscription")page="Home";currentPage=page;pageTransition=DateTime.UtcNow;foreach(var item in pages)item.Value.Visible=item.Key==page;foreach(var item in navigation){item.Value.Selected=item.Key==page;item.Value.Invalidate();}if(pages.TryGetValue(page,out var target)){FitPage(target);target.BringToFront();if(!preview)Motion.Reveal(target);}if(pageHost!=null)pageHost.Controls.OfType<Panel>().FirstOrDefault(p=>p.Height==40)?.BringToFront();UpdateSelectedSummary();}
 Panel Page(string key,string title,string subtitle){var panel=new ScrollPage{Dock=DockStyle.Fill,AutoScroll=false,Visible=false,Padding=new(0,0,0,42)};var stack=new BufferedFlow{AutoSize=true,FlowDirection=FlowDirection.TopDown,WrapContents=false,Padding=new(0,0,8,0)};stack.Controls.Add(Design.Label(title,22));stack.Controls.Add(Design.Label(subtitle,10,true));panel.SetContent(stack);pages[key]=panel;pageHost!.Controls.Add(panel);return stack;}
 static Card AddCard(Panel stack,int height){var card=new Card{Height=height,Width=760};stack.Controls.Add(card);return card;}
 static ModernButton Action(string text,int width=150)=>new(){Text=text,Width=width};
 void FitPage(Panel page){var stack=page.Controls.OfType<FlowLayoutPanel>().FirstOrDefault();if(stack==null)return;int width=Math.Max(500,page.ClientSize.Width-28);stack.Width=width;foreach(Control c in stack.Controls){if(c is Card||c is TableLayoutPanel||c is FlowLayoutPanel)c.Width=width-8;}}
 void BuildHome(){
  var home=new BufferedPanel{Dock=DockStyle.Fill,AutoScroll=false,Visible=false};pages["Home"]=home;pageHost!.Controls.Add(home);
  var layout=new BufferedTable{Dock=DockStyle.Fill,ColumnCount=1,RowCount=6,Padding=new(0,0,0,42)};
  foreach(var height in new[]{82,254,52,52,-1,112})layout.RowStyles.Add(height<0?new(SizeType.Percent,100):new(SizeType.Absolute,height));home.Controls.Add(layout);
  var heading=Design.Label("اتصال امن، با یک انتخاب",12);heading.Dock=DockStyle.Fill;heading.AutoSize=false;heading.TextAlign=ContentAlignment.MiddleLeft;var headingStack=new BufferedTable{Dock=DockStyle.Fill,RowCount=2,Margin=Padding.Empty};headingStack.RowStyles.Add(new(SizeType.Absolute,Math.Max(46,TextRenderer.MeasureText(heading.Text,Design.Font(16,FontStyle.Bold)).Height+10)));headingStack.RowStyles.Add(new(SizeType.Percent,100));heading.Tag=new TextStyle(16,false,FontStyle.Bold);headingStack.Controls.Add(heading,0,0);var tagline=Design.Label("سریع. خصوصی. بدون مرز.",10,true);tagline.Dock=DockStyle.Fill;headingStack.Controls.Add(tagline,0,1);layout.Controls.Add(headingStack,0,0);
  var top=new BufferedTable{Dock=DockStyle.Fill,ColumnCount=2,RowCount=1,Margin=new(0,0,0,10)};top.ColumnStyles.Add(new(SizeType.Absolute,430));top.ColumnStyles.Add(new(SizeType.Percent,100));layout.Controls.Add(top,0,1);
  var hero=new Card{ReflectionDelay=0,Dock=DockStyle.Fill,Padding=new(18),Margin=new(0,0,14,0),Tag="fixed-home"};var center=new BufferedTable{Dock=DockStyle.Fill,ColumnCount=2,RowCount=4};center.ColumnStyles.Add(new(SizeType.Absolute,146));center.ColumnStyles.Add(new(SizeType.Percent,100));foreach(var h in new[]{45,30,38,-1})center.RowStyles.Add(h<0?new(SizeType.Percent,100):new(SizeType.Absolute,h));power.Size=new(144,144);power.Anchor=AnchorStyles.None;stateTitle.Font=Design.Font(14);stateTitle.Tag=new TextStyle(13,false);stateHint.Font=Design.Font(9);stateHint.Tag=new TextStyle(9,true);serverSummary.Font=Design.Font(9);serverSummary.Tag=new TextStyle(9,false);foreach(var label in new[]{stateTitle,stateHint,serverSummary}){label.AutoSize=false;label.Dock=DockStyle.Fill;label.Margin=Padding.Empty;label.TextAlign=ContentAlignment.MiddleCenter;label.AutoEllipsis=true;}center.Controls.Add(power,0,0);center.SetRowSpan(power,4);center.Controls.Add(stateTitle,1,0);center.Controls.Add(stateHint,1,1);center.Controls.Add(serverSummary,1,2);center.SetRowSpan(serverSummary,2);hero.Controls.Add(center);top.Controls.Add(hero,0,0);
  var account=new Card{ReflectionDelay=2.4,Dock=DockStyle.Fill,Padding=new(22),Margin=Padding.Empty};var form=new BufferedTable{Dock=DockStyle.Fill,ColumnCount=2,RowCount=6,Margin=Padding.Empty};form.ColumnStyles.Add(new(SizeType.Percent,100));form.ColumnStyles.Add(new(SizeType.Absolute,150));foreach(var h in new[]{20,58,28,5,-1,54})form.RowStyles.Add(h<0?new(SizeType.Percent,100):new(SizeType.Absolute,h));
  var title=Design.Label("اشتراک من",12);title.AutoSize=false;title.Margin=Padding.Empty;title.Dock=DockStyle.Fill;form.Controls.Add(title,0,0);form.SetColumnSpan(title,2);groups.Dock=DockStyle.Fill;form.Controls.Add(groups,0,1);form.SetColumnSpan(groups,2);
  accountUsage.Tag=new TextStyle(11,false,FontStyle.Bold);accountUsage.Font=Design.Font(10);accountUsage.Dock=DockStyle.Fill;accountUsage.AutoSize=false;accountUsage.AutoEllipsis=true;accountUsage.Margin=new(4,7,4,0);form.Controls.Add(accountUsage,0,2);form.SetColumnSpan(accountUsage,2);
  accountProgress.Dock=DockStyle.Fill;accountProgress.Margin=new(4,0,4,0);form.Controls.Add(accountProgress,0,3);form.SetColumnSpan(accountProgress,2);accountExpiry.Dock=DockStyle.Fill;accountExpiry.AutoSize=false;accountExpiry.AutoEllipsis=true;accountExpiry.Margin=new(4,2,4,2);form.Controls.Add(accountExpiry,0,4);form.SetColumnSpan(accountExpiry,2);
  manageSubscription.IconGlyph="\uE710";refresh.IconGlyph="\uE777";editSubscription.IconGlyph="\uE70F";deleteSubscription.IconGlyph="\uE74D";var manage=manageSubscription;manage.Click+=(_,_)=>{if(singleConfigScope)ShowSingleConfigDialog();else ShowSubscriptionDialog();};StyleExisting(refresh);refresh.Width=110;refresh.Text="آپدیت";manage.Width=192;editSubscription.Width=188;editSubscription.Click+=(_,_)=>ShowEditSubscriptionDialog();deleteSubscription.Width=118;deleteSubscription.Click+=(_,_)=>DeleteSubscription();var actions=new BufferedTable{Dock=DockStyle.Fill,ColumnCount=4,RowCount=1,Margin=Padding.Empty};actions.RowStyles.Add(new(SizeType.Percent,100));foreach(var weight in new[]{31f,18f,32f,19f})actions.ColumnStyles.Add(new(SizeType.Percent,weight));var actionButtons=new[]{manage,refresh,editSubscription,deleteSubscription};for(int i=0;i<actionButtons.Length;i++){var button=actionButtons[i];button.AutoSize=false;button.Dock=DockStyle.Fill;button.Margin=new(i==0?0:4,5,i==3?0:4,5);button.Dock=DockStyle.Fill;button.Height=44;actions.Controls.Add(button,i,0);}form.Controls.Add(actions,0,5);form.SetColumnSpan(actions,2);account.Controls.Add(form);top.Controls.Add(account,1,0);
  var scope=new BufferedFlow{Dock=DockStyle.Fill,FlowDirection=FlowDirection.LeftToRight,WrapContents=false,Margin=Padding.Empty};subscriptionsTab.Width=140;singleConfigsTab.Width=220;foreach(var tab in new[]{subscriptionsTab,singleConfigsTab}){tab.Height=44;tab.Margin=new(0,0,8,0);scope.Controls.Add(tab);}layout.Controls.Add(scope,0,2);
  var toolbar=new BufferedTable{Dock=DockStyle.Fill,ColumnCount=8,RowCount=1,Margin=Padding.Empty};toolbar.ColumnStyles.Add(new(SizeType.Percent,100));foreach(var w in new[]{190,100,85,105,105,120,110})toolbar.ColumnStyles.Add(new(SizeType.Absolute,w));search.Font=filter.Font=Design.Font(9);search.Dock=DockStyle.Fill;filter.Dock=DockStyle.Fill;var favorite=Action("محبوب",120);favorite.IconGlyph="\uE734";favorite.Click+=(_,_)=>ToggleFavorite();var ping=Action("پینگ",105);ping.IconGlyph="\uE701";ping.AccessibleDescription=L("ICMP round-trip time to the server","زمان رفت و برگشت ICMP به سرور");ping.Click+=async(_,_)=>await CheckLatency();var pingAll=Action("پینگ همه",110);pingAll.IconGlyph="\uE701";pingAll.Click+=async(_,_)=>await CheckLatency(true);var ip=Action("IP خروجی",105);ip.Width=125;ip.IconGlyph="\uE707";ip.Click+=async(_,_)=>await RefreshIp();favoriteAction=favorite;pingAction=ping;pingAllAction=pingAll;publicIpAction=ip;foreach(var button in new[]{favorite,ping,pingAll,ip,editConfig,shareConfig}){button.Dock=DockStyle.Fill;button.Height=44;button.Margin=new(4,0,4,0);}toolbar.Controls.Add(search,0,0);toolbar.Controls.Add(filter,1,0);toolbar.Controls.Add(favorite,2,0);toolbar.Controls.Add(ping,3,0);toolbar.Controls.Add(pingAll,4,0);toolbar.Controls.Add(ip,5,0);editConfig.IconGlyph="\uE70F";shareConfig.IconGlyph="\uE72D";editConfig.Width=125;editConfig.Click+=async(_,_)=>await ShowConfigEditor();toolbar.Controls.Add(editConfig,6,0);shareConfig.Width=140;toolbar.Controls.Add(shareConfig,7,0);layout.Controls.Add(toolbar,0,3);
  var serverCard=new Card{ReflectionDelay=5.2,Dock=DockStyle.Fill,Padding=new(8),Margin=new(0,4,0,8)};serverCard.Controls.Add(servers);layout.Controls.Add(serverCard,0,4);
  var dashboard=new BufferedTable{Dock=DockStyle.Fill,ColumnCount=8,RowCount=1,Margin=Padding.Empty};for(int col=0;col<8;col++)dashboard.ColumnStyles.Add(new(SizeType.Percent,12.5f));dashboard.RowStyles.Add(new(SizeType.Percent,100));
  var items=new[]{("protocol","پروتکل"),("country","کشور"),("ping","پینگ تونل"),("ip","IP خروجی"),("duration","مدت اتصال"),("download","دانلود"),("upload","آپلود"),("usage","ترافیک نشست")};
  for(int i=0;i<items.Length;i++){var card=new BufferedPanel{Dock=DockStyle.Fill,Padding=new(4),Margin=new(2)};var rows=new BufferedTable{Dock=DockStyle.Fill,RowCount=2,ColumnCount=1};rows.RowStyles.Add(new(SizeType.Absolute,24));rows.RowStyles.Add(new(SizeType.Percent,100));var keyLabel=Design.Label(items[i].Item2,8,true);((StableLabel)keyLabel).IconGlyph=new[]{"\uE71B","\uE774","\uE945","\uE707","\uE823","\uE896","\uE898","\uE9D9"}[i];keyLabel.Tag=new TextStyle(7,true);keyLabel.Dock=DockStyle.Fill;keyLabel.Margin=Padding.Empty;var value=Design.Label("—",10);value.Dock=DockStyle.Fill;value.AutoSize=false;value.Margin=Padding.Empty;value.AutoEllipsis=true;value.TextAlign=ContentAlignment.MiddleRight;value.RightToLeft=RightToLeft.No;rows.Controls.Add(keyLabel,0,0);rows.Controls.Add(value,0,1);card.Controls.Add(rows);if(!metrics.TryGetValue(items[i].Item1,out var values))metrics[items[i].Item1]=values=new();values.Add(value);dashboard.Controls.Add(card,i,0);}var statistics=new Card{ReflectionDelay=7.1,Dock=DockStyle.Fill,Padding=new(14,9,14,9),Margin=new(0,12,0,0)};statistics.Controls.Add(dashboard);layout.Controls.Add(statistics,0,5);
  bool? compactLayout=null;
  void AdaptHome(){bool compact=home.Width<1060||home.Height<860;if(compactLayout==compact)return;compactLayout=compact;layout.SuspendLayout();toolbar.SuspendLayout();
   layout.Padding=new(0,0,0,compact?0:42);layout.RowStyles[0].Height=82;layout.RowStyles[1].Height=compact?222:254;layout.RowStyles[2].Height=compact?46:52;layout.RowStyles[3].Height=compact?96:52;layout.RowStyles[5].Height=compact?88:112;
   statistics.Padding=compact?new(14,4,14,4):new(14,9,14,9);top.ColumnStyles[0].Width=compact?350:430;account.Padding=new(compact?15:22);
   int[] accountRows=compact?new[]{18,58,26,5,100,48}:new[]{20,58,28,5,100,54};for(int i=0;i<accountRows.Length;i++)form.RowStyles[i].Height=accountRows[i];
   toolbar.ColumnStyles.Clear();toolbar.RowStyles.Clear();toolbar.ColumnCount=compact?12:8;toolbar.RowCount=compact?2:1;
   if(compact){for(int col=0;col<12;col++)toolbar.ColumnStyles.Add(new(SizeType.Percent,100f/12));toolbar.RowStyles.Add(new(SizeType.Percent,50));toolbar.RowStyles.Add(new(SizeType.Percent,50));toolbar.SetCellPosition(search,new(0,0));toolbar.SetColumnSpan(search,7);toolbar.SetCellPosition(filter,new(7,0));toolbar.SetColumnSpan(filter,5);int i=0;foreach(var button in new[]{favorite,ping,pingAll,ip,editConfig,shareConfig}){toolbar.SetCellPosition(button,new(i*2,1));toolbar.SetColumnSpan(button,2);i++;}}
   else{toolbar.ColumnStyles.Add(new(SizeType.Percent,100));foreach(var w in new[]{190,100,85,105,105,120,110})toolbar.ColumnStyles.Add(new(SizeType.Absolute,w));int i=0;foreach(Control control in new Control[]{search,filter,favorite,ping,pingAll,ip,editConfig,shareConfig}){toolbar.SetColumnSpan(control,1);toolbar.SetCellPosition(control,new(i++,0));}}
   toolbar.ResumeLayout(true);layout.ResumeLayout(true);
  }
  home.Resize+=(_,_)=>AdaptHome();AdaptHome();
 }
 void Metric(string key,string value){if(metrics.TryGetValue(key,out var controls))foreach(var c in controls){var direction=Design.Persian(value)?RightToLeft.Yes:RightToLeft.No;if(c.RightToLeft!=direction)c.RightToLeft=direction;if(c.TextAlign!=ContentAlignment.MiddleRight)c.TextAlign=ContentAlignment.MiddleRight;if(c.Text!=value)c.Text=value;}}
 void InitializeServerControls(){filter.Items.AddRange(new object[]{"همهٔ سرورها","علاقه‌مندی‌ها","اخیراً استفاده‌شده"});filter.SelectedIndex=0;foreach(var title in new[]{"سرور","کشور","پروتکل","پینگ","وضعیت","بار","★"})servers.Columns.Add(title);}
 void BuildSettings(){var stack=Page("Settings","تنظیمات","تنظیمات ظاهر و رفتار برنامه");var active=AddCard(stack,450);var column=new BufferedFlow{Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false};var dark=new ModernToggle{Text="تم تاریک",Checked=preferences.Dark};dark.CheckedChanged+=(_,_)=>{preferences.Dark=dark.Checked;Design.Dark=dark.Checked;SavePreferences();RefreshThemeGeometry(this);ApplyTheme(this);Invalidate(true);Update();};var notifications=new ModernToggle{Text="اعلان تغییر وضعیت اتصال",Checked=preferences.Notifications};notifications.CheckedChanged+=(_,_)=>{preferences.Notifications=notifications.Checked;SavePreferences();};var language=new ModernSelect{Width=300,AccessibleName="Language"};language.Items.AddRange(new object[]{"English","فارسی"});language.SelectedIndex=preferences.Language=="fa"?1:0;language.SelectedIndexChanged+=(_,_)=>{preferences.Language=language.SelectedIndex==1?"fa":"en";SavePreferences();ApplyLanguage();};var visualStyle=new ModernSelect{Width=300,AccessibleName="Visual style"};visualStyle.Items.AddRange(new object[]{"Melavo Classic","Melavo Glass"});visualStyle.SelectedIndex=preferences.VisualStyle=="glass"?1:0;visualStyle.SelectedIndexChanged+=(_,_)=>{preferences.VisualStyle=visualStyle.SelectedIndex==1?"glass":"classic";Design.Glass=preferences.VisualStyle=="glass";SavePreferences();RefreshThemeGeometry(this);ApplyTheme(this);Motion.Reveal(pages["Settings"]);};var automaticAppUpdates=new ModernToggle{Text=L("Download app updates automatically","دریافت خودکار به‌روزرسانی برنامه"),Checked=preferences.AutoAppUpdate,Width=450};automaticAppUpdates.CheckedChanged+=async(_,_)=>{preferences.AutoAppUpdate=automaticAppUpdates.Checked;SavePreferences();if(preferences.AutoAppUpdate)await CheckAppUpdates();};column.Controls.AddRange(new Control[]{automaticAppUpdates,Design.Label(L("Visual style","سبک ظاهری"),10,true),visualStyle,dark,notifications,tun,Design.Label("Language / زبان",10,true),language});active.Controls.Add(column);
 }
 void BuildAbout(){var stack=Page("About","درباره","Melavo VPN · Windows Client");var about=AddCard(stack,170);var label=installedInfo;label.AutoSize=false;label.Dock=DockStyle.Fill;about.Controls.Add(label);var diagnostic=AddCard(stack,250);var title=Design.Label("جزئیات وضعیت و خطا",12);title.AutoSize=false;title.Height=36;title.Dock=DockStyle.Top;details.BorderStyle=BorderStyle.None;details.Font=Design.Font(9);diagnostic.Controls.Add(details);diagnostic.Controls.Add(title);var copy=Action("کپی جزئیات خطا",175);copy.Click+=(_,_)=>{if(!string.IsNullOrEmpty(details.Text))Clipboard.SetText(details.Text);};stack.Controls.Add(copy);BuildUpdateCard(stack);}
 void StyleExisting(ModernButton b){b.FlatStyle=FlatStyle.Flat;b.FlatAppearance.BorderColor=Design.Border;b.BackColor=Design.Surface;b.ForeColor=Design.Text;b.Height=38;b.AutoSize=false;b.Width=135;}
 static bool UnderCard(Control control){for(var parent=control.Parent;parent!=null;parent=parent.Parent)if(parent is Card)return true;return false;}
 void ApplyTheme(Control root){root.BackColor=root is Form?Design.Canvas:root is Card||root is ModernInput||root is ModernSelect||root is ServerList?Design.Surface:(root.Parent?.BackColor is Color parentColor&&parentColor.A==255?parentColor:UnderCard(root)?Design.Surface:Design.Canvas);if(Design.Glass&&(root is Label||root is Panel||root is TableLayoutPanel||root is FlowLayoutPanel)&&root is not Card)root.BackColor=Color.Transparent;root.ForeColor=Design.Text;if(root is Label l){if(l.Tag is TextStyle style)l.ForeColor=style.Muted?Design.Muted:Design.Text;if(l.TextAlign!=ContentAlignment.MiddleCenter){l.RightToLeft=metrics.Values.Any(values=>values.Contains(l))?RightToLeft.No:Fa?RightToLeft.Yes:RightToLeft.No;l.TextAlign=ContentAlignment.MiddleLeft;}}foreach(Control child in root.Controls)ApplyTheme(child);if(root is Card card)card.SyncMaterial();if(root is ModernInput input)input.SyncTheme();if(root is Form&&root.IsHandleCreated)NativeTheme.Window(root.Handle);root.Invalidate();}
 string ProfileKey(JsonObject profile){var groupId=(groups.SelectedItem as SubscriptionGroup)?.Id??"";return Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(groupId+profile.ToJsonString())));}
 static JsonNode? Outbound(JsonObject p)=>p["outbounds"]?.AsArray().FirstOrDefault(x=>x?["protocol"]?.ToString() is not ("freedom" or "blackhole" or "dns"));
 static string Country(JsonObject p){var text=p["remarks"]?.ToString()??"";var runes=text.EnumerateRunes().Select(r=>r.Value).ToArray();for(int i=0;i<runes.Length-1;i++)if(runes[i] is >=0x1F1E6 and <=0x1F1FF&&runes[i+1] is >=0x1F1E6 and <=0x1F1FF){var code=""+(char)('A'+runes[i]-0x1F1E6)+(char)('A'+runes[i+1]-0x1F1E6);return char.ConvertFromUtf32(runes[i])+char.ConvertFromUtf32(runes[i+1])+" "+code;}return "Unknown";}
 bool fillingServers;
 void FillServers(){if(servers.Columns.Count<7)return;_ = servers.Handle;int oldOffset=servers.ScrollOffset;fillingServers=true;int oldTop=servers.TopItem?.Tag is int topIndex?topIndex:-1;int old=servers.SelectedItems.Count>0&&servers.SelectedItems[0].Tag is int n?n:-1;servers.BeginUpdate();servers.Items.Clear();for(int i=0;i<Profiles.Count;i++){var p=Profiles[i];var key=ProfileKey(p);var title=p["remarks"]?.ToString()??$"Server {i+1}";var protocol=Outbound(p)?["protocol"]?.ToString()?.ToUpperInvariant()??"—";var country=Country(p);if(!string.IsNullOrWhiteSpace(search.Text)&&!($"{title} {protocol} {country}").Contains(search.Text,StringComparison.OrdinalIgnoreCase))continue;if(filter.SelectedIndex==1&&!preferences.Favorites.Contains(key))continue;if(filter.SelectedIndex==2&&!preferences.Recent.Contains(key))continue;var item=new ServerItem(title){Tag=i};item.SubItems.Add(country);item.SubItems.Add(protocol);item.SubItems.Add(latency.TryGetValue(key,out var ping)?ping+" ms":latencyFailed.Contains(key)?L("No ICMP reply","بدون پاسخ ICMP"):"—");item.SubItems.Add(latency.ContainsKey(key)?L("ICMP reply","پاسخ ICMP"):latencyFailed.Contains(key)?L("No reply","بدون پاسخ"):L("Not tested","بررسی نشده"));item.SubItems.Add("—");item.SubItems.Add(preferences.Favorites.Contains(key)?"★":"☆");servers.Items.Add(item);}if(filter.SelectedIndex==2){var sorted=servers.Items.Cast<ServerItem>().OrderBy(x=>preferences.Recent.IndexOf(ProfileKey(Profiles[(int)x.Tag!]))).ToArray();servers.Items.Clear();servers.Items.AddRange(sorted);}var choice=servers.Items.Cast<ServerItem>().FirstOrDefault(x=>(int)x.Tag! ==old)??servers.Items.Cast<ServerItem>().FirstOrDefault();if(choice!=null)choice.Selected=true;servers.EmptyDescription=Profiles.Count>0?L("Try a different search or server filter.","جستجو یا فیلتر سرورها را تغییر دهید."):L("Add a subscription or import a configuration\nto see available servers.","برای نمایش سرورها، ساب اضافه کنید\nیا یک کانفیگ وارد کنید.");servers.EndUpdate();FitColumns();servers.RestoreTop(oldTop,oldOffset);fillingServers=false;UpdateSelectedSummary();SetControls();}
 void FitColumns(){if(servers.Columns.Count<7)return;int[] widths={Math.Max(220,servers.ClientSize.Width-580),90,145,95,140,65,45};for(int i=0;i<7;i++)if(servers.Columns[i].Width!=widths[i])servers.Columns[i].Width=widths[i];}
 void UpdateSelectedSummary(){var selected=servers.SelectedItems.Count>0&&servers.SelectedItems[0].Tag is int i&&i<Profiles.Count?Profiles[i]:null;var p=(xray!=null||busy)&&activeProfileKey!=null?Profiles.FirstOrDefault(profile=>ProfileKey(profile)==activeProfileKey):selected;if(p!=null){serverSummary.Text=ServerList.StripFlags(p["remarks"]?.ToString()??"Server");serverSummary.RightToLeft=Design.Persian(serverSummary.Text)?RightToLeft.Yes:RightToLeft.No;Metric("protocol",Outbound(p)?["protocol"]?.ToString()?.ToUpperInvariant()??"—");Metric("country",Country(p).Split(' ').Last());Metric("ping",latency.TryGetValue(ProfileKey(p),out var ping)?ping+" ms":"—");}else{serverSummary.Text=L("Select a server to connect.","یک سرور برای اتصال انتخاب کنید");Metric("protocol","—");Metric("country","—");Metric("ping","—");}if(groups.SelectedItem is SubscriptionGroup g)groupDescription.Text=L($"{g.Name} · {g.Profiles.Count} servers · Last updated: ",$"{g.Name} · {g.Profiles.Count} سرور · آخرین آپدیت: ")+(g.Updated?.ToLocalTime().ToString("yyyy/MM/dd HH:mm")??"—");UpdateAccount();}
 void ToggleFavorite(){if(busy||updating||servers.SelectedItems.Count==0)return;var p=Profiles[(int)servers.SelectedItems[0].Tag!];var key=ProfileKey(p);if(!preferences.Favorites.Add(key))preferences.Favorites.Remove(key);SavePreferences();FillServers();}
 void SavePreferences(){if(preview)return;try{preferences.Save();}catch{status.Text=L("Could not save appearance settings.","ذخیرهٔ تنظیمات ظاهر ناموفق بود.");}}
 void SyncUi(){if(pageHost==null)return;search.Enabled=filter.Enabled=!busy&&!updating;var next=disconnecting?ConnectionState.Disconnecting:busy?ConnectionState.Connecting:xray!=null?ConnectionState.Connected:status.Text.Contains("ناموفق")||status.Text.Contains("متوقف شد")||status.Text.Contains("Connection failed")||status.Text.Contains("Engine stopped")?ConnectionState.Error:ConnectionState.Disconnected;
  if(next!=visualState){if(next==ConnectionState.Connected){connectedAt=DateTime.UtcNow;sampled=false;totalRx=totalTx=0;if(activeProfileKey!=null){preferences.Recent.Remove(activeProfileKey);preferences.Recent.Insert(0,activeProfileKey);preferences.Recent=preferences.Recent.Take(12).ToList();SavePreferences();}}if(next is ConnectionState.Disconnected or ConnectionState.Error){connectedAt=null;Metric("ip","—");}if(preferences.Notifications){tray.Visible=true;tray.ShowBalloonTip(2500,"Melavo VPN",next.ToString(),ToolTipIcon.Info);}visualState=next;UpdateSelectedSummary();if(next==ConnectionState.Connected&&!preview)_=RefreshIp();}
  bool stateChanged=power.State!=next;power.State=next;power.Enabled=!updating&&!busy&&!disconnecting;power.AccessibleName=next==ConnectionState.Connected?L("Disconnect VPN","قطع اتصال VPN"):L("Connect VPN","اتصال VPN");if(stateChanged)power.Invalidate();var title=next switch{ConnectionState.Connected=>"متصل",ConnectionState.Connecting=>"در حال اتصال",ConnectionState.Disconnecting=>"در حال قطع اتصال",ConnectionState.Error=>"خطای اتصال",_=>"متصل نیست"};stateTitle.Text=Fa?title:English.GetValueOrDefault(title,title);stateTitle.RightToLeft=Fa?RightToLeft.Yes:RightToLeft.No;stateTitle.ForeColor=next==ConnectionState.Error?Design.Error:next==ConnectionState.Connected?Design.Accent:Design.Text;var hint=next switch{ConnectionState.Connected=>(status.Text.Contains("پاسخ تست")||status.Text.Contains("did not respond"))?"تونل فعال؛ اینترنت هنوز تأیید نشده":"اتصال فعال است",ConnectionState.Connecting=>status.Text,ConnectionState.Disconnecting=>"در حال قطع اتصال",ConnectionState.Error=>"خطای اتصال؛ جزئیات در «درباره»",_=>updating?"به‌روزرسانی ساب‌ها…":"برای اتصال دکمه را بزنید"};stateHint.Text=Fa?hint:English.GetValueOrDefault(hint,hint);Metric("duration",connectedAt.HasValue?(DateTime.UtcNow-connectedAt.Value).ToString(@"hh\:mm\:ss"):"—");}
 void SampleTraffic(){if(xray==null){Metric("download","—");Metric("upload","—");return;}if(box==null){SampleSocksTraffic();return;}try{var nic=NetworkInterface.GetAllNetworkInterfaces().FirstOrDefault(n=>n.Name=="MelavoTUN");if(nic==null)return;var s=nic.GetIPStatistics();if(sampled){var seconds=Math.Max(.1,(DateTime.UtcNow-sampleAt).TotalSeconds);var rx=Math.Max(0,s.BytesReceived-lastRx);var tx=Math.Max(0,s.BytesSent-lastTx);totalRx+=rx;totalTx+=tx;Metric("download",Bytes((long)(rx/seconds))+"/s");Metric("upload",Bytes((long)(tx/seconds))+"/s");Metric("usage",Bytes(totalRx+totalTx));Metric("rx",Bytes(totalRx));Metric("tx",Bytes(totalTx));}lastRx=s.BytesReceived;lastTx=s.BytesSent;sampled=true;sampleAt=DateTime.UtcNow;}catch{}}
 static string Bytes(long n)=>n>=1073741824?$"{n/1073741824d:0.00} GB":n>=1048576?$"{n/1048576d:0.0} MB":n>=1024?$"{n/1024d:0.0} KB":$"{n} B";
 void UpdateAccount(){if(singleConfigScope){accountProgress.Visible=accountExpiry.Visible=false;accountUsage.Text=groups.SelectedItem is SubscriptionGroup local?L($"{local.Profiles.Count} single configurations",$"{local.Profiles.Count} کانفیگ تکی"):L("No single configurations yet","هنوز کانفیگ تکی اضافه نشده");accountUsage.RightToLeft=Fa?RightToLeft.Yes:RightToLeft.No;return;}accountProgress.Visible=accountExpiry.Visible=true;if(groups.SelectedItem is not SubscriptionGroup g){accountProgress.Visible=false;accountUsage.Text=L("No subscription yet","هنوز اشتراکی اضافه نشده");accountExpiry.Text=L("Add a subscription to see its account details","ساب را برای نمایش اطلاعات حساب اضافه کنید");accountProgress.Value=0;return;}if(g.TotalBytes is >0&&g.UsedBytes.HasValue){accountProgress.Visible=true;accountUsage.Text=L($"{Bytes(g.UsedBytes.Value)} / {Bytes(g.TotalBytes.Value)} used · {Bytes(Math.Max(0,g.TotalBytes.Value-g.UsedBytes.Value))} left",$"مصرف: \u200e{Bytes(g.UsedBytes.Value)} / {Bytes(g.TotalBytes.Value)}\u200e · باقی‌مانده: \u200e{Bytes(Math.Max(0,g.TotalBytes.Value-g.UsedBytes.Value))}\u200e");accountProgress.Value=(int)Math.Clamp(g.UsedBytes.Value/(double)g.TotalBytes.Value*1000,0,1000);}else{accountProgress.Visible=false;accountUsage.Text=L("Traffic allowance is not provided by this subscription","حجم اشتراک توسط ساب گزارش نشده");accountProgress.Value=0;}accountUsage.RightToLeft=Design.Persian(accountUsage.Text)?RightToLeft.Yes:RightToLeft.No;accountExpiry.RightToLeft=Fa?RightToLeft.Yes:RightToLeft.No;accountExpiry.Text=!Fa&&g.ExpiresUnix is >0?$"Expires {DateTimeOffset.FromUnixTimeSeconds(g.ExpiresUnix.Value).LocalDateTime:yyyy/MM/dd} · {Math.Max(0,(int)Math.Ceiling((DateTimeOffset.FromUnixTimeSeconds(g.ExpiresUnix.Value)-DateTimeOffset.UtcNow).TotalDays))} days left":g.ExpiresUnix is >0?$"انقضا: \u200e{DateTimeOffset.FromUnixTimeSeconds(g.ExpiresUnix.Value).LocalDateTime:yyyy/MM/dd}\u200e · {Math.Max(0,(int)Math.Ceiling((DateTimeOffset.FromUnixTimeSeconds(g.ExpiresUnix.Value)-DateTimeOffset.UtcNow).TotalDays))} روز باقی‌مانده":L("Expiry date is not provided by this subscription","تاریخ انقضا توسط ساب گزارش نشده");}
}
















