namespace MelavoClient;
static class FlagPainter {
 public static bool Draw(Graphics g,Rectangle bounds,string code){var r=new Rectangle(bounds.Left+3,bounds.Top+(bounds.Height-15)/2,23,15);void Fill(Color color,int y,int h){using var b=new SolidBrush(color);g.FillRectangle(b,new Rectangle(r.X,y,r.Width,h));}switch(code){case "DE":Fill(Color.FromArgb(35,35,35),r.Y,5);Fill(Color.FromArgb(187,53,59),r.Y+5,5);Fill(Color.FromArgb(230,193,80),r.Y+10,5);break;case "NL":Fill(Color.FromArgb(181,54,67),r.Y,5);Fill(Color.WhiteSmoke,r.Y+5,5);Fill(Color.FromArgb(51,81,142),r.Y+10,5);break;case "FI":Fill(Color.WhiteSmoke,r.Y,15);using(var b=new SolidBrush(Color.FromArgb(44,86,151))){g.FillRectangle(b,r.X+6,r.Y,4,15);g.FillRectangle(b,r.X,r.Y+6,23,4);}break;case "FR":Fill(Color.WhiteSmoke,r.Y,15);using(var blue=new SolidBrush(Color.FromArgb(46,71,143)))g.FillRectangle(blue,r.X,r.Y,8,15);using(var red=new SolidBrush(Color.FromArgb(191,62,73)))g.FillRectangle(red,r.X+16,r.Y,7,15);break;
  case "BG":Fill(Color.WhiteSmoke,r.Y,5);Fill(Color.FromArgb(40,133,95),r.Y+5,5);Fill(Color.FromArgb(185,53,63),r.Y+10,5);break;
  case "SE":Fill(Color.FromArgb(41,100,157),r.Y,15);using(var yellow=new SolidBrush(Color.FromArgb(241,202,62))){g.FillRectangle(yellow,r.X+6,r.Y,3,15);g.FillRectangle(yellow,r.X,r.Y+6,23,3);}break;
  case "TR":var redColor=Color.FromArgb(196,49,63);Fill(redColor,r.Y,15);using(var white=new SolidBrush(Color.WhiteSmoke))g.FillEllipse(white,r.X+5,r.Y+3,9,9);using(var red=new SolidBrush(redColor))g.FillEllipse(red,r.X+7,r.Y+2,8,10);var points=Enumerable.Range(0,10).Select(i=>{double a=-Math.PI/2+i*Math.PI/5;double length=i%2==0?3:1.2;return new PointF(r.X+16+(float)(Math.Cos(a)*length),r.Y+7.5f+(float)(Math.Sin(a)*length));}).ToArray();using(var white=new SolidBrush(Color.WhiteSmoke))g.FillPolygon(white,points);break;
  case "US":Fill(Color.WhiteSmoke,r.Y,15);using(var red=new SolidBrush(Color.FromArgb(176,55,69)))for(int i=0;i<13;i+=2)g.FillRectangle(red,r.X,r.Y+i*15f/13,r.Width,15f/13);using(var blue=new SolidBrush(Color.FromArgb(49,67,118)))g.FillRectangle(blue,r.X,r.Y,10,8);using(var white=new SolidBrush(Color.WhiteSmoke))for(int row=0;row<9;row++)for(int col=0;col<(row%2==0?6:5);col++)g.FillRectangle(white,r.X+.7f+col*1.5f+(row%2==0?0:.7f),r.Y+.5f+row*.8f,.5f,.5f);break;
  default:return false;}using var pen=new Pen(Design.Border);g.DrawRectangle(pen,r);return true;}
}
