<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <Version>0.8.2</Version>
    <DefineConstants Condition="'$(CustomerEdition)' == 'true'">$(DefineConstants);CUSTOMER_EDITION</DefineConstants>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Assets\Melavo.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Melavo.ico" /><EmbeddedResource Include="Assets\GlassWallpaper.png" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
  </ItemGroup>
</Project>



