<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <Version>0.9.2</Version>
    <DefineConstants Condition="'$(CustomerEdition)' == 'true'">$(DefineConstants);CUSTOMER_EDITION</DefineConstants>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Assets\Melavo.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\WebShell.html" /><EmbeddedResource Include="Assets\WebShell.js" /><EmbeddedResource Include="Assets\CoreHashes.json" /><EmbeddedResource Include="Assets\Melavo.ico" /><EmbeddedResource Include="Assets\GlassWallpaper.jpg" /><PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3537.50" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
  </ItemGroup>
<Target Name="UseOnlyWinFormsWebView" BeforeTargets="ResolveAssemblyReferences"><ItemGroup><Reference Remove="@(Reference)" Condition="'%(Reference.Filename)' == 'Microsoft.Web.WebView2.Wpf'" /></ItemGroup></Target>
</Project>
