using System.IO.Compression;
using System.Text.Json;
namespace MelavoClient;
static class UpdateChecks {
 public static int Run(){var root=Path.Combine(AppContext.BaseDirectory,"update-tests-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);var report=new List<string>();var staged=new List<string>();void Assert(bool condition,string name){if(!condition)throw new Exception("Updater regression: "+name);report.Add("PASS: "+name);}
  try{var exe=Path.Combine(AppContext.BaseDirectory,"MelavoClient.exe");var digest=UpdateService.Hash(exe);UpdateService.ValidateExe(exe);void Package(string file,string hash,bool traversal=false){using var zip=ZipFile.Open(file,ZipArchiveMode.Create);zip.CreateEntryFromFile(exe,"MelavoClient.exe");var manifest=new{app="MelavoClient",edition=SubscriptionStore.Edition,version="0.7.0",files=new Dictionary<string,string>{{"MelavoClient.exe",hash}}};using(var text=new StreamWriter(zip.CreateEntry("release.json").Open()))text.Write(JsonSerializer.Serialize(manifest));if(traversal){using var text=new StreamWriter(zip.CreateEntry("../outside.txt").Open());text.Write("should never extract");}}
   var good=Path.Combine(root,"good.zip");Package(good,digest);var plan=UpdateService.PreparePackage(good);staged.Add(plan.Stage);Assert(plan.Version=="0.7.0"&&UpdateService.Hash(Path.Combine(plan.Stage,"MelavoClient.exe"))==digest,"valid package staging and SHA256");File.WriteAllText(Path.Combine(AppContext.BaseDirectory,"update-worker-check.ps1"),UpdateService.WorkerScript(plan,Path.Combine(root,"target's app"),0));
   var bad=Path.Combine(root,"bad-hash.zip");Package(bad,new string('0',64));bool rejected=false;try{UpdateService.PreparePackage(bad);}catch{rejected=true;}Assert(rejected,"corrupted package rejected");
   var unsafeZip=Path.Combine(root,"traversal.zip");Package(unsafeZip,digest,true);rejected=false;try{UpdateService.PreparePackage(unsafeZip);}catch{rejected=true;}Assert(rejected&&!File.Exists(Path.Combine(root,"outside.txt")),"ZIP traversal rejected");
   var candidate=Path.Combine(root,"candidate");var target=Path.Combine(root,"fake-core");Directory.CreateDirectory(candidate);Directory.CreateDirectory(target);File.WriteAllText(Path.Combine(candidate,"geoip.dat"),"new-data");File.WriteAllText(Path.Combine(candidate,"libcronet.dll"),"new-library");File.WriteAllText(Path.Combine(target,"geoip.dat"),"original-data");File.WriteAllText(Path.Combine(target,"libcronet.dll"),"original-library");using(var locked=new FileStream(Path.Combine(target,"libcronet.dll"),FileMode.Open,FileAccess.ReadWrite,FileShare.None)){rejected=false;try{UpdateService.ApplyCore(candidate,target);}catch{rejected=true;}Assert(rejected&&File.ReadAllText(Path.Combine(target,"geoip.dat"))=="original-data","core rollback after locked-file failure");}
   UpdateService.ApplyCore(candidate,target);Assert(File.ReadAllText(Path.Combine(target,"geoip.dat"))=="new-data"&&File.ReadAllText(Path.Combine(target,"libcronet.dll"))=="new-library","core install in isolated test directory");
   File.WriteAllLines(Path.Combine(AppContext.BaseDirectory,"update-checks.txt"),report);return 0;
  }finally{if(Path.GetFullPath(root).StartsWith(Path.GetFullPath(AppContext.BaseDirectory),StringComparison.OrdinalIgnoreCase))Directory.Delete(root,true);foreach(var stage in staged)if(Path.GetFullPath(stage).StartsWith(Path.GetFullPath(UpdateService.TempRoot)+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase))Directory.Delete(stage,true);}
 }
}
