using System.IO.Compression;
using System.Text.Json;
namespace MelavoClient;
static class UpdateChecks {
 sealed class PackageResponse(byte[] bytes):HttpMessageHandler{protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,CancellationToken cancellation)=>Task.FromResult(new HttpResponseMessage(System.Net.HttpStatusCode.OK){Content=new ByteArrayContent(bytes)});}
 public static int Run(){var root=Path.Combine(AppContext.BaseDirectory,"update-tests-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);var report=new List<string>();var staged=new List<string>();void Assert(bool condition,string name){if(!condition)throw new Exception("Updater regression: "+name);report.Add("PASS: "+name);}
  try{var exe=Path.Combine(AppContext.BaseDirectory,"MelavoClient.exe");var digest=UpdateService.Hash(exe);UpdateService.ValidateExe(exe);void Package(string file,string hash,bool traversal=false){using var zip=ZipFile.Open(file,ZipArchiveMode.Create);zip.CreateEntryFromFile(exe,"MelavoClient.exe");var manifest=new{app="MelavoClient",edition=SubscriptionStore.Edition,version="9.0.0",files=new Dictionary<string,string>{{"MelavoClient.exe",hash}}};using(var text=new StreamWriter(zip.CreateEntry("release.json").Open()))text.Write(JsonSerializer.Serialize(manifest));if(traversal){using var text=new StreamWriter(zip.CreateEntry("../outside.txt").Open());text.Write("should never extract");}}
   var good=Path.Combine(root,"good.zip");Package(good,digest);var plan=UpdateService.PreparePackage(good);staged.Add(plan.Stage);Assert(plan.Version=="9.0.0"&&UpdateService.Hash(Path.Combine(plan.Stage,"MelavoClient.exe"))==digest,"valid package staging and SHA256");Assert(plan.Files.Contains("release.json"),"installed manifest is updated with executable");Assert(!UpdateService.WorkerScript(plan,root,0,false).Contains("Start-Process"),"automatic installation respects app exit");
   var releaseJson=System.Text.Json.Nodes.JsonNode.Parse("{\"tag_name\":\"v9.0.0\",\"draft\":false,\"prerelease\":false,\"assets\":[]}")!.AsObject();releaseJson["assets"]!.AsArray().Add(new System.Text.Json.Nodes.JsonObject{["name"]="Melavo-VPN-9.0.0-Windows-x64.zip",["state"]="uploaded",["size"]=new FileInfo(good).Length,["digest"]="sha256:"+UpdateService.Hash(good),["browser_download_url"]="https://github.com/sirvan1133/MelavoClient/releases/download/v9.0.0/Melavo-VPN-9.0.0-Windows-x64.zip"});
   var appRelease=UpdateService.ParseAppRelease(releaseJson)!;Assert(appRelease!=null&&appRelease.Version=="9.0.0","official Windows release selected");releaseJson["prerelease"]=true;Assert(UpdateService.ParseAppRelease(releaseJson)==null,"prereleases ignored");releaseJson["prerelease"]=false;releaseJson["tag_name"]="v0.6.10";Assert(UpdateService.ParseAppRelease(releaseJson)==null,"older releases do not downgrade app");releaseJson["tag_name"]="v9.0.0";releaseJson["assets"]![0]!["browser_download_url"]="https://github.com/other/MelavoClient/releases/download/v9.0.0/a.zip";bool invalidRepo=false;try{UpdateService.ParseAppRelease(releaseJson);}catch{invalidRepo=true;}Assert(invalidRepo,"foreign release download rejected");
   using(var mockHttp=new HttpClient(new PackageResponse(File.ReadAllBytes(good)))){var downloaded=UpdateService.DownloadApp(appRelease!,testHttp:mockHttp).GetAwaiter().GetResult();staged.Add(downloaded.Stage);Assert(downloaded.Version=="9.0.0","automatic download validates and stages package");}
   using(var mockHttp=new HttpClient(new PackageResponse(File.ReadAllBytes(good)))){bool invalidDigest=false;try{UpdateService.DownloadApp(appRelease! with{Sha256=new string('0',64)},testHttp:mockHttp).GetAwaiter().GetResult();}catch{invalidDigest=true;}Assert(invalidDigest,"automatic download rejects corrupt digest");}
   File.WriteAllText(Path.Combine(AppContext.BaseDirectory,"update-worker-check.ps1"),UpdateService.WorkerScript(plan,Path.Combine(root,"target's app"),0));
   var bad=Path.Combine(root,"bad-hash.zip");Package(bad,new string('0',64));bool rejected=false;try{UpdateService.PreparePackage(bad);}catch{rejected=true;}Assert(rejected,"corrupted package rejected");
   var unsafeZip=Path.Combine(root,"traversal.zip");Package(unsafeZip,digest,true);rejected=false;try{UpdateService.PreparePackage(unsafeZip);}catch{rejected=true;}Assert(rejected&&!File.Exists(Path.Combine(root,"outside.txt")),"ZIP traversal rejected");
   var candidate=Path.Combine(root,"candidate");var target=Path.Combine(root,"fake-core");Directory.CreateDirectory(candidate);Directory.CreateDirectory(target);File.WriteAllText(Path.Combine(candidate,"geoip.dat"),"new-data");File.WriteAllText(Path.Combine(candidate,"libcronet.dll"),"new-library");File.WriteAllText(Path.Combine(target,"geoip.dat"),"original-data");File.WriteAllText(Path.Combine(target,"libcronet.dll"),"original-library");using(var locked=new FileStream(Path.Combine(target,"libcronet.dll"),FileMode.Open,FileAccess.ReadWrite,FileShare.None)){rejected=false;try{UpdateService.ApplyCore(candidate,target);}catch{rejected=true;}Assert(rejected&&File.ReadAllText(Path.Combine(target,"geoip.dat"))=="original-data","core rollback after locked-file failure");}
   UpdateService.ApplyCore(candidate,target);Assert(File.ReadAllText(Path.Combine(target,"geoip.dat"))=="new-data"&&File.ReadAllText(Path.Combine(target,"libcronet.dll"))=="new-library","core install in isolated test directory");
   File.WriteAllLines(Path.Combine(AppContext.BaseDirectory,"update-checks.txt"),report);return 0;
  }finally{if(Path.GetFullPath(root).StartsWith(Path.GetFullPath(AppContext.BaseDirectory),StringComparison.OrdinalIgnoreCase))Directory.Delete(root,true);foreach(var stage in staged)if(Path.GetFullPath(stage).StartsWith(Path.GetFullPath(UpdateService.TempRoot)+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase))Directory.Delete(stage,true);}
 }
}
