package org.melavo.vpn;
import android.app.*;
import android.content.*;
import android.net.*;
import android.os.*;
import android.webkit.*;
import android.graphics.*;
import android.util.Base64;
import org.json.*;
import java.util.*;
import java.util.concurrent.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import com.google.zxing.*;
import com.google.zxing.common.BitMatrix;
import libv2ray.Libv2ray;

public final class MainActivity extends Activity {
 WebView web;SecureStore store;String selectedId="",pendingVpn="",status="",updateStatus="",directIp="—";boolean ready,busy,wasConnected;long autoCheckAt;final Handler handler=new Handler(Looper.getMainLooper());final ExecutorService worker=Executors.newSingleThreadExecutor();String exportText;byte[] exportQr;
 @Override public void onCreate(Bundle state){super.onCreate(state);try{store=new SecureStore(this);}catch(Exception e){new AlertDialog.Builder(this).setTitle("Melavo VPN").setMessage("Could not decrypt saved data. Original data was preserved.").setPositiveButton("Close",(d,w)->finish()).show();return;}
  go.Seq.setContext(getApplicationContext());web=new WebView(this);if(Build.VERSION.SDK_INT<26)web.setLayerType(android.view.View.LAYER_TYPE_SOFTWARE,null);android.widget.FrameLayout frame=new android.widget.FrameLayout(this);frame.setBackgroundColor(Color.rgb(10,14,26));frame.addView(web,new android.widget.FrameLayout.LayoutParams(-1,-1));setContentView(frame);if(Build.VERSION.SDK_INT>=30){getWindow().setDecorFitsSystemWindows(false);frame.setOnApplyWindowInsetsListener((view,insets)->{android.graphics.Insets bars=insets.getInsets(android.view.WindowInsets.Type.systemBars()|android.view.WindowInsets.Type.displayCutout());android.graphics.Insets ime=insets.getInsets(android.view.WindowInsets.Type.ime());view.setPadding(bars.left,bars.top,bars.right,Math.max(bars.bottom,ime.bottom));return insets;});}web.setBackgroundColor(Color.rgb(10,14,26));web.getSettings().setJavaScriptEnabled(true);web.getSettings().setDomStorageEnabled(false);web.getSettings().setAllowFileAccess(false);web.getSettings().setAllowContentAccess(false);web.getSettings().setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);web.getSettings().setSupportMultipleWindows(false);WebView.setWebContentsDebuggingEnabled((getApplicationInfo().flags&android.content.pm.ApplicationInfo.FLAG_DEBUGGABLE)!=0);
  web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView view,WebResourceRequest request){return true;}@Override public WebResourceResponse shouldInterceptRequest(WebView view,WebResourceRequest request){String url=request.getUrl().toString();if(!url.startsWith("data:")&&!url.equals("https://melavo.local/"))return new WebResourceResponse("text/plain","utf-8",new ByteArrayInputStream(new byte[0]));return null;}});
  web.addJavascriptInterface(new Bridge(),"MelavoNative");try{String html=new String(readAsset("ui.html"),StandardCharsets.UTF_8);web.loadDataWithBaseURL("https://melavo.local/",html,"text/html","UTF-8",null);}catch(Exception e){status=e.getMessage();}
  handler.postDelayed(tick,1000);
 }
 byte[] readAsset(String name)throws IOException{try(InputStream in=getAssets().open(name)){return read(in,6_000_000);}}
 static byte[] read(InputStream in,int max)throws IOException{ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1){if(out.size()+n>max)throw new IOException("Response too large");out.write(b,0,n);}return out.toByteArray();}
 final Runnable tick=new Runnable(){public void run(){if(!isFinishing()&&!worker.isShutdown()){worker.execute(()->{try{sendState();if(SystemClock.elapsedRealtime()-autoCheckAt>60000){autoCheckAt=SystemClock.elapsedRealtime();autoRefresh();}}catch(Exception ignored){}});handler.postDelayed(this,1000);}}};
 String tr(String en,String fa){try{return store.preferences().optString("language","en").equals("fa")?fa:en;}catch(Exception ignored){return en;}}
 final class Bridge {@JavascriptInterface public void postMessage(String json){if(json.length()>5_100_000||worker.isShutdown())return;worker.execute(()->{int id=0;String original=store.data.toString();try{JSONObject message=new JSONObject(json);id=message.getInt("id");Object result=command(message);sendState();emit(new JSONObject().put("type","reply").put("id",id).put("result",result==null?JSONObject.NULL:result));}catch(Exception e){try{store.data=new JSONObject(original);emit(new JSONObject().put("type","reply").put("id",id).put("error",e.getMessage()==null?"Operation failed":e.getMessage()));sendState();}catch(Exception ignored){}}});}}
 void emit(JSONObject message){String payload=message.toString();handler.post(()->{if(web!=null&&!isFinishing())web.evaluateJavascript("window.__melavoReceive&&window.__melavoReceive({data:"+payload+"});",null);});}
 void idle()throws Exception{if(MelavoVpnService.running||MelavoVpnService.connecting)throw new Exception(tr("Disconnect before making changes.","پیش از ویرایش، اتصال را قطع کنید."));}
 JSONObject group(String id)throws Exception{JSONArray groups=store.groups();for(int i=0;i<groups.length();i++)if(groups.getJSONObject(i).optString("id").equals(id))return groups.getJSONObject(i);throw new Exception("Subscription not found");}
 Object command(JSONObject m)throws Exception{
  String action=m.getString("action"),nodeId=m.optString("nodeId");
  if(action.equals("ready")){ready=true;status=tr("Disconnected","قطع");worker.execute(()->{try{directIp=fetchTrace(null);if(store.preferences().optBoolean("autoUpdate",true)){boolean available=AndroidUpdater.check(this,true);updateStatus=available?tr("An update is ready to install.","آپدیت آماده نصب است."):tr("Melavo is up to date.","ملـاوو به‌روز است.");}}catch(Exception e){updateStatus=tr("Could not check updates.","بررسی آپدیت انجام نشد.");}});return true;}
  if(action.equals("preferences")){JSONObject preferences=store.preferences();for(String key:new String[]{"language","theme","appearance","tun","autoUpdate","notifications","tray"})if(m.has(key))preferences.put(key,m.get(key));store.save();return true;}
  if(action.equals("select")){store.node(nodeId);selectedId=nodeId;return true;}
  if(action.equals("github")){handler.post(()->startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://github.com/sirvan1133"))));return true;}
  if(action.equals("close")){handler.post(this::finish);return true;}
  if(action.equals("drag")||action.equals("maximize")||action.equals("minimize"))return true;
  busy=true;sendState();try{
   switch(action){
    case "toggle-connect":case "connect":
     if(MelavoVpnService.running&&action.equals("toggle-connect")){status=tr("Disconnected","قطع");startService(new Intent(this,MelavoVpnService.class).setAction("stop"));return true;}
     store.node(nodeId);selectedId=nodeId;pendingVpn=nodeId;handler.post(()->{Intent consent=android.net.VpnService.prepare(this);if(consent!=null)startActivityForResult(consent,100);else startVpn();});status=tr("Starting VPN…","راه‌اندازی VPN…");return true;
    case "add-config":{
     idle();JSONArray configs=ConfigCodec.parse(m.getString("text"));if(configs.length()!=1)throw new Exception(tr("Enter exactly one configuration.","فقط یک کانفیگ وارد کنید."));JSONObject singles=null;JSONArray groups=store.groups();for(int i=0;i<groups.length();i++)if(!groups.getJSONObject(i).optBoolean("subscription"))singles=groups.getJSONObject(i);if(singles==null){singles=new JSONObject().put("id",UUID.randomUUID().toString()).put("name","Single configurations").put("url","").put("subscription",false).put("nodes",new JSONArray());groups.put(singles);}JSONObject n=SecureStore.nodeFor(configs.getJSONObject(0));n.put("single",true);singles.getJSONArray("nodes").put(n);store.save();status=tr("Configuration saved.","کانفیگ ذخیره شد.");return true;
    }
    case "add-sub":case "edit-sub":{
     idle();String name=m.getString("name").trim(),url=m.getString("url").trim();if(name.isEmpty()||!url.startsWith("https://"))throw new Exception(tr("Enter a name and a valid HTTPS URL.","نام و لینک معتبر HTTPS را وارد کنید."));JSONObject g=action.equals("edit-sub")?group(m.getString("groupId")):new JSONObject().put("id",UUID.randomUUID().toString()).put("subscription",true);JSONArray groups=store.groups();for(int i=0;i<groups.length();i++){JSONObject other=groups.getJSONObject(i);if(other.optString("url").equals(url)&&!other.optString("id").equals(g.getString("id")))throw new Exception(tr("Subscription already exists.","ساب قبلاً اضافه شده است."));}
     if(!url.equals(g.optString("url"))){status=tr("Downloading subscription…","دریافت ساب…");sendState();refresh(g,url);}g.put("name",name).put("url",url).put("autoUpdate",m.optBoolean("autoUpdate",true)).put("interval",Math.max(1,Math.min(168,m.optInt("interval",12))));if(action.equals("add-sub"))groups.put(g);store.save();status=tr("Subscription saved.","ساب ذخیره شد.");return true;
    }
    case "refresh":{
     idle();JSONArray groups=store.groups();for(int i=0;i<groups.length();i++){JSONObject g=groups.getJSONObject(i);if(g.optBoolean("subscription")&&(m.optString("groupId").isEmpty()||m.optString("groupId").equals(g.getString("id"))))refresh(g,g.getString("url"));}store.save();status=tr("Subscriptions updated.","ساب‌ها آپدیت شدند.");return true;
    }
    case "delete-sub":{idle();JSONArray old=store.groups(),next=new JSONArray();for(int i=0;i<old.length();i++)if(!old.getJSONObject(i).getString("id").equals(m.getString("groupId")))next.put(old.get(i));store.data.put("groups",next);store.save();return true;}
    case "delete-node":{idle();JSONArray groups=store.groups();for(int i=0;i<groups.length();i++){JSONObject g=groups.getJSONObject(i);JSONArray old=g.getJSONArray("nodes"),next=new JSONArray();for(int j=0;j<old.length();j++)if(!old.getJSONObject(j).getString("id").equals(nodeId))next.put(old.get(j));g.put("nodes",next);}store.save();return true;}
    case "edit-data":{idle();JSONObject node=store.node(nodeId),config=new JSONObject(node.getJSONObject("config").toString());config.remove("_shareLink");return new JSONObject().put("name",node.getString("name")).put("text",config.toString(2));}
    case "edit-node":{idle();JSONArray parsed=ConfigCodec.parse(m.getString("text"));if(parsed.length()!=1)throw new Exception("Enter exactly one configuration");JSONObject config=parsed.getJSONObject(0);config.put("remarks",m.optString("name"));config.remove("_shareLink");JSONObject node=store.node(nodeId);JSONObject replacement=SecureStore.nodeFor(config);replacement.put("id",node.getString("id")).put("single",node.optBoolean("single"));Iterator<String> keys=replacement.keys();while(keys.hasNext()){String key=keys.next();node.put(key,replacement.get(key));}node.put("edited",true);store.save();return true;}
    case "copy":{String text=ConfigCodec.share(store.node(nodeId).getJSONObject("config"));handler.post(()->((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("Melavo configuration",text)));return true;}
    case "share":{String text=ConfigCodec.share(store.node(nodeId).getJSONObject("config"));String png=null,error=null;try{png=Base64.encodeToString(qr(text),Base64.NO_WRAP);}catch(Exception e){error=e.getMessage();}return new JSONObject().put("text",text).put("qr",png==null?JSONObject.NULL:png).put("qrError",error==null?JSONObject.NULL:error);}
    case "save-qr":{exportQr=qr(ConfigCodec.share(store.node(nodeId).getJSONObject("config")));handler.post(()->{Intent picker=new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("image/png").putExtra(Intent.EXTRA_TITLE,"Melavo-configuration.png");startActivityForResult(picker,102);});return true;}
    case "ping":case "ping-all":{
     JSONArray groups=store.groups();for(int i=0;i<groups.length();i++){JSONArray nodes=groups.getJSONObject(i).getJSONArray("nodes");for(int j=0;j<nodes.length();j++){JSONObject n=nodes.getJSONObject(j);if(action.equals("ping")&&!n.getString("id").equals(nodeId))continue;try{long ms=icmp(ConfigCodec.host(n.getJSONObject("config")));n.put("ping",ms).put("failed",false);}catch(Exception e){n.put("ping",JSONObject.NULL).put("failed",true);}sendState();}}return true;
    }
    case "ip":if(MelavoVpnService.running)MelavoVpnService.publicIp=fetchProxyIp();return true;
    case "clear-logs":MelavoVpnService.error="";return true;
    case "export-logs":exportText=MelavoVpnService.error;handler.post(()->startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("text/plain").putExtra(Intent.EXTRA_TITLE,"Melavo-diagnostics.txt"),103));return true;
    case "app-update":case "core-update":idle();updateStatus=tr("Checking GitHub and downloading verified APK…","بررسی گیت‌هاب و دریافت APK تأییدشده…");sendState();boolean downloaded=AndroidUpdater.check(this,true);updateStatus=downloaded?tr("An update is ready. Tap Install update.","آپدیت آماده است؛ نصب آپدیت را بزنید."):tr("Melavo is up to date.","ملـاوو به‌روز است.");return true;
    case "local-update":handler.post(()->AndroidUpdater.install(this));return true;
    default:throw new Exception("Unknown action");
   }
  }finally{busy=false;}
 }
 void startVpn(){Intent intent=new Intent(this,MelavoVpnService.class).putExtra("nodeId",pendingVpn);if(Build.VERSION.SDK_INT>=26)startForegroundService(intent);else startService(intent);}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==100){if(result==RESULT_OK)startVpn();else status=tr("VPN permission was cancelled.","اجازه VPN لغو شد.");}if(result==RESULT_OK&&data!=null&&(request==102||request==103)){try(OutputStream out=getContentResolver().openOutputStream(data.getData())){out.write(request==102?exportQr:exportText.getBytes(StandardCharsets.UTF_8));}catch(Exception e){status=e.getMessage();}}}
 void refresh(JSONObject group,String url)throws Exception{HttpsFetch result=https(url);JSONArray configs=ConfigCodec.parse(result.text),old=group.optJSONArray("nodes"),nodes=new JSONArray();for(int i=0;i<configs.length();i++){JSONObject config=configs.getJSONObject(i),node=SecureStore.nodeFor(config);if(old!=null)for(int j=0;j<old.length();j++){JSONObject previous=old.getJSONObject(j);JSONObject source=previous.optJSONObject("source");if(source==null)source=previous.getJSONObject("config");if(source.optJSONArray("outbounds").toString().equals(config.getJSONArray("outbounds").toString())){node.put("id",previous.getString("id"));if(previous.optBoolean("edited")){node=new JSONObject(previous.toString());}break;}}node.put("source",config).put("single",false);nodes.put(node);}group.put("nodes",nodes).put("updated",System.currentTimeMillis());if(result.account!=null)for(String part:result.account.split(";")){String[] p=part.trim().split("=",2);if(p.length==2)try{group.put(p[0],Long.parseLong(p[1]));}catch(Exception ignored){}}}
 static final class HttpsFetch { final String text,account; HttpsFetch(String text,String account){this.text=text;this.account=account;} }
 static HttpsFetch https(String url)throws Exception{URL address=new URL(url);if(!address.getProtocol().equals("https"))throw new Exception("Only HTTPS subscriptions are supported");HttpURLConnection c=(HttpURLConnection)address.openConnection(java.net.Proxy.NO_PROXY);c.setConnectTimeout(15000);c.setReadTimeout(30000);c.setRequestProperty("User-Agent","v2rayN/7.0");try{int code=c.getResponseCode();if(code/100!=2)throw new Exception("HTTP "+code);return new HttpsFetch(new String(read(c.getInputStream(),5_000_000),StandardCharsets.UTF_8),c.getHeaderField("subscription-userinfo"));}finally{c.disconnect();}}
 static String fetchTrace(java.net.Proxy proxy)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL("https://www.cloudflare.com/cdn-cgi/trace").openConnection(proxy==null?java.net.Proxy.NO_PROXY:proxy);c.setConnectTimeout(8000);c.setReadTimeout(8000);try{String text=new String(read(c.getInputStream(),20000),StandardCharsets.UTF_8);for(String line:text.split("\n"))if(line.startsWith("ip="))return line.substring(3).trim();throw new Exception("IP unavailable");}finally{c.disconnect();}}
 static String fetchProxyIp()throws Exception{
  java.net.Socket socket=new java.net.Socket();socket.connect(new InetSocketAddress("127.0.0.1",17890),8000);socket.setSoTimeout(8000);
  try{InputStream in=socket.getInputStream();OutputStream out=socket.getOutputStream();out.write(new byte[]{5,1,0});out.flush();if(in.read()!=5||in.read()!=0)throw new IOException("SOCKS negotiation failed");byte[] host="www.cloudflare.com".getBytes(StandardCharsets.US_ASCII);ByteArrayOutputStream request=new ByteArrayOutputStream();request.write(new byte[]{5,1,0,3,(byte)host.length});request.write(host);request.write(new byte[]{1,(byte)187});out.write(request.toByteArray());out.flush();if(in.read()!=5||in.read()!=0)throw new IOException("SOCKS connection failed");in.read();int type=in.read(),length=type==1?4:type==4?16:type==3?in.read():-1;if(length<0)throw new IOException("Invalid SOCKS reply");for(int i=0;i<length+2;i++)if(in.read()<0)throw new EOFException();
   javax.net.ssl.SSLSocket tls=(javax.net.ssl.SSLSocket)((javax.net.ssl.SSLSocketFactory)javax.net.ssl.SSLSocketFactory.getDefault()).createSocket(socket,"www.cloudflare.com",443,true);javax.net.ssl.SSLParameters parameters=tls.getSSLParameters();parameters.setEndpointIdentificationAlgorithm("HTTPS");tls.setSSLParameters(parameters);tls.setSoTimeout(8000);tls.startHandshake();tls.getOutputStream().write("GET /cdn-cgi/trace HTTP/1.1\r\nHost: www.cloudflare.com\r\nConnection: close\r\n\r\n".getBytes(StandardCharsets.US_ASCII));tls.getOutputStream().flush();String response=new String(read(tls.getInputStream(),20000),StandardCharsets.UTF_8);if(!response.startsWith("HTTP/1.1 200")&&!response.startsWith("HTTP/1.0 200"))throw new IOException("IP service unavailable");for(String line:response.split("\n"))if(line.startsWith("ip=")){String address=line.substring(3).trim();if(address.matches("[0-9a-fA-F:.]+"))return address;}throw new IOException("IP unavailable");
  }finally{socket.close();}
 }
 static long icmp(String host)throws Exception{InetAddress address=InetAddress.getByName(host);String binary=address instanceof Inet6Address?"/system/bin/ping6":"/system/bin/ping";java.lang.Process process=new ProcessBuilder(binary,"-c","3","-W","2",address.getHostAddress()).redirectErrorStream(true).start();long deadline=SystemClock.elapsedRealtime()+8000;while(true){try{process.exitValue();break;}catch(IllegalThreadStateException waiting){if(SystemClock.elapsedRealtime()>deadline){process.destroy();throw new Exception("No ICMP reply");}Thread.sleep(40);}}String text=new String(read(process.getInputStream(),16000),StandardCharsets.UTF_8);java.util.regex.Matcher matcher=java.util.regex.Pattern.compile("time[=<]([0-9.]+)").matcher(text);ArrayList<Double> samples=new ArrayList<>();while(matcher.find())samples.add(Double.parseDouble(matcher.group(1)));if(samples.isEmpty())throw new Exception("No ICMP reply");Collections.sort(samples);return Math.round(samples.get(samples.size()/2));}
 static byte[] qr(String text)throws Exception{Map<EncodeHintType,Object> hints=new EnumMap<>(EncodeHintType.class);hints.put(EncodeHintType.CHARACTER_SET,"UTF-8");hints.put(EncodeHintType.MARGIN,4);BitMatrix matrix=new com.google.zxing.qrcode.QRCodeWriter().encode(text,BarcodeFormat.QR_CODE,512,512,hints);Bitmap image=Bitmap.createBitmap(matrix.getWidth(),matrix.getHeight(),Bitmap.Config.ARGB_8888);int[] pixels=new int[matrix.getWidth()*matrix.getHeight()];for(int y=0;y<matrix.getHeight();y++)for(int x=0;x<matrix.getWidth();x++)pixels[y*matrix.getWidth()+x]=matrix.get(x,y)?Color.BLACK:Color.WHITE;image.setPixels(pixels,0,matrix.getWidth(),0,0,matrix.getWidth(),matrix.getHeight());ByteArrayOutputStream bytes=new ByteArrayOutputStream();image.compress(Bitmap.CompressFormat.PNG,100,bytes);image.recycle();return bytes.toByteArray();}
 void autoRefresh()throws Exception{if(busy||MelavoVpnService.running||MelavoVpnService.connecting)return;boolean changed=false;JSONArray groups=store.groups();for(int i=0;i<groups.length();i++){JSONObject g=groups.getJSONObject(i);if(g.optBoolean("subscription")&&g.optBoolean("autoUpdate",true)&&System.currentTimeMillis()-g.optLong("updated",0)>=Math.max(1,g.optInt("interval",12))*3600000L){try{refresh(g,g.getString("url"));changed=true;}catch(Exception ignored){}}}if(changed)store.save();}
 static String bytes(long value){return value>=1_073_741_824L?String.format(Locale.US,"%.2f GB",value/1073741824d):value>=1_048_576?String.format(Locale.US,"%.1f MB",value/1048576d):value>=1024?String.format(Locale.US,"%.1f KB",value/1024d):value+" B";}
 void sendState()throws Exception{if(!ready)return;JSONObject prefs=store.preferences();JSONArray groups=store.groups(),publicGroups=new JSONArray();for(int i=0;i<groups.length();i++){JSONObject g=groups.getJSONObject(i),copy=new JSONObject(g.toString());JSONArray nodes=g.getJSONArray("nodes"),safeNodes=new JSONArray();for(int j=0;j<nodes.length();j++){JSONObject n=new JSONObject(nodes.getJSONObject(j).toString());n.remove("config");n.remove("source");safeNodes.put(n);}copy.put("nodes",safeNodes);if(g.has("total"))copy.put("used",bytes(g.optLong("upload")+g.optLong("download"))).put("total",bytes(g.optLong("total")));if(g.has("expire"))copy.put("expires",new java.text.SimpleDateFormat("yyyy/MM/dd",Locale.US).format(new java.util.Date(g.getLong("expire")*1000)));publicGroups.put(copy);}
  boolean connected=MelavoVpnService.running;if(wasConnected&&!connected)status=tr("Disconnected","قطع");wasConnected=connected;String active=connected?MelavoVpnService.activeId:selectedId,server="",ping="—";try{JSONObject node=store.node(active);server=node.getString("name");if(!node.isNull("ping"))ping=node.getLong("ping")+" ms";}catch(Exception ignored){}
  long seconds=connected?(SystemClock.elapsedRealtime()-MelavoVpnService.started)/1000:0;String currentStatus=!MelavoVpnService.error.isEmpty()?tr("Connection failed: ","خطای اتصال: ")+MelavoVpnService.error:connected?tr("Connected","متصل"):status;
  JSONObject state=new JSONObject().put("version","0.9.2").put("groups",publicGroups).put("language",prefs.optString("language","en")).put("theme",prefs.optString("theme","dark-blue")).put("appearance",prefs.optJSONObject("appearance")==null?new JSONObject():prefs.getJSONObject("appearance")).put("connected",connected).put("connecting",MelavoVpnService.connecting).put("disconnecting",false).put("error",!MelavoVpnService.error.isEmpty()).put("busy",busy||MelavoVpnService.connecting).put("selectedId",selectedId).put("activeId",MelavoVpnService.activeId).put("serverName",server).put("download",connected?bytes(MelavoVpnService.download)+"/s":"—").put("upload",connected?bytes(MelavoVpnService.upload)+"/s":"—").put("duration",connected?String.format(Locale.US,"%02d:%02d:%02d",seconds/3600,seconds/60%60,seconds%60):"—").put("usage",connected?bytes(MelavoVpnService.totalDownload+MelavoVpnService.totalUpload):"—").put("ping",ping).put("ip",connected?MelavoVpnService.publicIp:"—").put("directIp",directIp).put("country","—").put("isp","—").put("socks",connected?"127.0.0.1:17890":"—").put("tun",true).put("tray",false).put("notifications",prefs.optBoolean("notifications",true)).put("autoUpdate",prefs.optBoolean("autoUpdate",true)).put("engines",Libv2ray.checkVersionX()).put("updateStatus",updateStatus).put("updateReady",new File(getFilesDir(),"updates/ready.apk").exists()).put("status",currentStatus).put("logs",MelavoVpnService.error);
  emit(new JSONObject().put("type","state").put("state",state));
 }
 @Override public void onBackPressed(){web.evaluateJavascript("(()=>{const modal=document.querySelector('.modal-overlay.show');if(modal){closeModal(modal.id);return true;}if(currentPage!=='servers'){showPage('servers');return true;}return false;})()",value->{if(!"true".equals(value))super.onBackPressed();});}
 @Override protected void onDestroy(){handler.removeCallbacks(tick);worker.shutdownNow();if(web!=null){web.removeJavascriptInterface("MelavoNative");web.destroy();web=null;}super.onDestroy();}
}
