pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }
dependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS); repositories { maven { url 'https://redirector.gvt1.com/edgedl/android/maven2' }; google(); mavenCentral() } }
rootProject.name='MelavoAndroid'
include ':app'

include ':probe'
